import requests, json, os
from datetime import datetime

FIREBASE_REFRESH_TOKEN = os.environ.get("FIREBASE_REFRESH_TOKEN")
FIREBASE_API_KEY = os.environ.get("FIREBASE_API_KEY")
GROUP_CODE = "F3XVPHFW"

def get_fresh_jwt():
    url = f"https://securetoken.googleapis.com/v1/token?key={FIREBASE_API_KEY}"
    r = requests.post(url, json={"grant_type":"refresh_token","refresh_token":FIREBASE_REFRESH_TOKEN}, timeout=15)
    r.raise_for_status()
    return r.json()["id_token"]

def fetch_leaderboard(jwt):
    url = f"https://api.dacopa.com/groups/{GROUP_CODE}/leaderboard"
    headers = {
        "Authorization": f"Bearer {jwt}",
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Origin": "https://app.dacopa.com",
        "X-Client-Capabilities": "predictions-v2"
    }
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    return r.json()

USERS_RAW = [
    ("gabriela.gomes","Corporativo","Brasil"),("tomas.martins","Corporativo","Brasil"),
    ("joyce.vasconcelos","Corporativo","Brasil"),("amanda.dias","Corporativo","Brasil"),
    ("filipe.faleiro","Corporativo","Brasil"),("carolina.villa","Corporativo","Brasil"),
    ("andre.marasco","Corporativo","Brasil"),("gustavo.guedez","Corporativo","Brasil"),
    ("jose.silva","BikeSampa","Brasil"),("mauro.rodrigues","BikeSampa","Brasil"),
    ("sandro.santos","BikeSampa","Brasil"),("wellington.cavalcante","BikeSampa","Brasil"),
    ("johnny.cana","BikeSampa","Brasil"),("hernani.silva","BikeSampa","Brasil"),
    ("tadeu.junior","BikeSampa","Brasil"),("marcos.cardoso","BikeSampa","Brasil"),
    ("sabrina.silva","Corporativo","Brasil"),("vinicius.arruda","BikeSampa","Brasil"),
    ("felipe.asantos","BikeSampa","Brasil"),("vinicius.figueiredo","BikeSampa","Brasil"),
    ("jhonattan.francisco","BikeSampa","Brasil"),("natalia.giordani","Corporativo","Brasil"),
    ("raul.sousa","BikeSampa","Brasil"),("alice.waquil","Corporativo","Brasil"),
    ("andre.bifulco","Corporativo","Brasil"),("valquiria.silva","Corporativo","Brasil"),
    ("antonio.ferreira","Corporativo","Brasil"),("debora.oliveira","Corporativo","Brasil"),
    ("shirleide.martins","Corporativo","Brasil"),("eduardo.lima","BikeSampa","Brasil"),
    ("rafael.bento","BikeSampa","Brasil"),("thailane.sacerdote","Corporativo","Brasil"),
    ("ariane.pina","Corporativo","Brasil"),("flavio.pangracio","Corporativo","Brasil"),
    ("gabriel.dacome","BikeSampa","Brasil"),("sthefany.simioni","Corporativo","Brasil"),
    ("gustavo.torquato","Corporativo","Brasil"),("yago.caetano","Corporativo","Brasil"),
    ("michelle.silva","BikeSampa","Brasil"),("luana.silva","Corporativo","Brasil"),
    ("fernando.fernandes","Corporativo","Brasil"),("alexandro.pereda","BikeSampa","Brasil"),
    ("cleriston.santos","BikeSampa","Brasil"),("marcos.silva","Corporativo","Brasil"),
    ("natalia.cunha","Corporativo","Brasil"),("paulo.freitas","Corporativo","Brasil"),
    ("victor.dantas","Corporativo","Brasil"),("wellington.soares","Corporativo","Brasil"),
    ("kelvis.rojas","BikeSampa","Brasil"),("mario.araujo","Corporativo","Brasil"),
    ("vinicius.pires","Corporativo","Brasil"),("olivia.mitne","Corporativo","Brasil"),
    ("alex.souza","BikeSampa","Brasil"),("gabriela.silva","Corporativo","Brasil"),
    ("ulisses.oliveira","Corporativo","Brasil"),("yasmin.goncalves","Corporativo","Brasil"),
    ("caroline.nascimento","Corporativo","Brasil"),("julia.jesus","Corporativo","Brasil"),
    ("gabriel.lopes","Corporativo","Brasil"),("luiza.lopes","Corporativo","Brasil"),
    ("fabio.pereira","BikeSampa","Brasil"),("rui.souza","Corporativo","Brasil"),
    ("josue.sombra","BikeSampa","Brasil"),("carlos.pereira","BikeSampa","Brasil"),
    ("guilherme.baldissera","Corporativo","Brasil"),("wesley.marcelino","Corporativo","Brasil"),
    ("icaro.uchoa","BikeSampa","Brasil"),("roberto.dias","Corporativo","Brasil"),
    ("barbara.sousa","BikeSampa","Brasil"),("cristovao.pereira","BikeSampa","Brasil"),
    ("daniel.aquino","BikeSampa","Brasil"),("matheus.vieira","BikeSampa","Brasil"),
    ("elayne.armas","BikeSampa","Brasil"),("leonardo.braga","BikeSampa","Brasil"),
    ("italo.barros","Corporativo","Brasil"),("mariana.pontel","Corporativo","Brasil"),
    ("xaiene.silva","BikeSampa","Brasil"),("marcos.barreto","Corporativo","Brasil"),
    ("vitorya.santos","Corporativo","Brasil"),("alexandre.rosa","Corporativo","Brasil"),
    ("juliana.miranda","BikeSampa","Brasil"),("carlos.roldan","BikeSampa","Brasil"),
    ("amanda.leite","BikeSampa","Brasil"),("emerson.soares","Corporativo","Brasil"),
    ("willian.silva","Corporativo","Brasil"),("julya.silva","Corporativo","Brasil"),
    ("waldomiro.feitosa","BikeSampa","Brasil"),("heitor.piovesan","Corporativo","Brasil"),
    ("yean.rodriguez","BikeSampa","Brasil"),("bruno.martins","Corporativo","Brasil"),
    ("sueli.nascimento","Corporativo","Brasil"),("sirleide.paz","Corporativo","Brasil"),
    ("victor.falcao","Corporativo","Brasil"),("thiago.boufelli","Corporativo","Brasil"),
    ("lizandra.lacerda","Corporativo","Brasil"),("marcos.santos","Corporativo","Brasil"),
    ("roberta.jorge","Corporativo","Brasil"),("bianca.oliveira","Corporativo","Brasil"),
    ("felipe.rodrigues","BikeSampa","Brasil"),("aline.menezes","Corporativo","Brasil"),
    ("dyego.franciscato","Corporativo","Brasil"),("matheus.ferreira","BikeSampa","Brasil"),
    ("josiene.souza","Corporativo","Brasil"),("elias.rodriguez","BikeSampa","Brasil"),
    ("eloise.tripodi","Corporativo","Brasil"),("maria.souza","Corporativo","Brasil"),
    ("vinicius.cassimiro","BikeSampa","Brasil"),("leonardo.luz","BikeSampa","Brasil"),
    ("wellington.conceicao","BikeSampa","Brasil"),("antonio.felipe","Corporativo","Brasil"),
    ("paulo.martins","BikeSampa","Brasil"),("gabriel.braz","Corporativo","Brasil"),
    ("tanyfer.oliveira","Corporativo","Brasil"),("erika.jesus","Corporativo","Brasil"),
    ("ana.cagnotto","Corporativo","Brasil"),("bruno.bezerra","BikeSampa","Brasil"),
    ("jade.silva","Corporativo","Brasil"),("alexsander.goes","BikeSampa","Brasil"),
    ("lucas.andrade","BikeSampa","Brasil"),("victor.neto","BikeSampa","Brasil"),
    ("eduarda.oliveira","Corporativo","Brasil"),("matheus.alves","BikeSampa","Brasil"),
    ("marjorie.morais","BikeSampa","Brasil"),("thiago.roque","Corporativo","Brasil"),
    ("andressa.souza","Corporativo","Brasil"),("mauricio.villar","Corporativo","Brasil"),
    ("eduardo.goncalves","BikeSampa","Brasil"),("paulo.andrade","BikeSampa","Brasil"),
    ("elisangela.sampaio","Corporativo","Brasil"),("caio.santos","BikeSampa","Brasil"),
    ("jhenifer.silva","Corporativo","Brasil"),("joao.pecin","BikeSampa","Brasil"),
    ("beatriz.silva","Corporativo","Brasil"),("stephane.oliveira","BikeSampa","Brasil"),
    ("angelo.dourado","BikeSampa","Brasil"),("iris.nunes","BikeSampa","Brasil"),
    ("angela.silva","BikeSampa","Brasil"),("leonardo.hohne","Corporativo","Brasil"),
    ("joycy.fernandes","BikeSampa","Brasil"),("tatiane.silva","BikeSampa","Brasil"),
    ("barbara.fortesa","Corporativo","Brasil"),("gleicy.oliveira","Corporativo","Brasil"),
    ("rodrigo.canola","Corporativo","Brasil"),("mariana.cardoso","Corporativo","Brasil"),
    ("cinthia.ramos","BikeSampa","Brasil"),("andreza.silva","Corporativo","Brasil"),
    ("vanessa.santos","Corporativo","Brasil"),("julia.lira","Corporativo","Brasil"),
    ("alan.pereira","Corporativo","Brasil"),("vinicius.paula","Corporativo","Brasil"),
    ("vitor.monteiro","Corporativo","Brasil"),("matheus.barbosa","BikeSampa","Brasil"),
    ("tiago.soares","Corporativo","Brasil"),("felipe.fernandes","Corporativo","Brasil"),
    ("bianca.andrade","BikeSampa","Brasil"),("gustavo.alves","BikeSampa","Brasil"),
    ("marina.brondani","Corporativo","Brasil"),("andersom.fontoura","BikeSampa","Brasil"),
    ("igor.monteiro","BikeSampa","Brasil"),("gerson.junior","BikeSampa","Brasil"),
    ("lucas.barbosa","BikeSampa","Brasil"),("elisangela.corticeiro","BikeSampa","Brasil"),
    ("paloma.santos","Corporativo","Brasil"),("diogo.csilva","BikeSampa","Brasil"),
    ("alvaro.santos","BikeSampa","Brasil"),("izaque.scomparim","Corporativo","Brasil"),
    ("bianca.rodrigues","Corporativo","Brasil"),("lucas.snascimento","BikeSampa","Brasil"),
    ("henrique.maitan","Corporativo","Brasil"),("gabriel.nascimento","Corporativo","Brasil"),
    ("pablo.nascimento","Corporativo","Brasil"),("higor.carvalho","BikeSampa","Brasil"),
    ("afonso.felippe","BikeSampa","Brasil"),("rafaella.silbermann","Corporativo","Brasil"),
    ("caio.lima","BikeSampa","Brasil"),("joao.urzedo","Corporativo","Brasil"),
    ("richard.ciriaco","BikeSampa","Brasil"),("marcos.paulo","BikeSampa","Brasil"),
    ("biatriz.ruas","Corporativo","Brasil"),("mayra.marquete","Corporativo","Brasil"),
    ("lucas.messa","Corporativo","Brasil"),("sabrina.castro","Corporativo","Brasil"),
    ("demosthenes.junior","BikePE","Brasil"),("daniel.silva","Corporativo","Brasil"),
    ("bruno.valdez","BikeRio","Brasil"),("charles.barreto","Corporativo","Brasil"),
    ("karoline.jesus","BikeSampa","Brasil"),("pedro.febronio","BikeSampa","Brasil"),
    ("aldo.caterina","Corporativo","Brasil"),("carlos.spereira","BikeSampa","Brasil"),
    ("beatriz.martins","Corporativo","Brasil"),("gustavo.nascimento","BikeSampa","Brasil"),
    ("deborah.medeiros","Corporativo","Brasil"),("thyalison.santos","BikeSampa","Brasil"),
    ("newton.sozza","Corporativo","Brasil"),("alexandre.oliveira","BikeSampa","Brasil"),
    ("carlos.gonzaga","BikeSampa","Brasil"),("juan.lima","BikeSampa","Brasil"),
    ("rafael.melo","BikeSampa","Brasil"),("gabriel.svieira","BikeSampa","Brasil"),
    ("victor.prado","BikeSampa","Brasil"),("kathleen.silva","Corporativo","Brasil"),
    ("jose.bezerra","BikePE","Brasil"),("sergio.silva","BikePE","Brasil"),
    ("antonio.rodrigues","BikePE","Brasil"),("francisco.junior","BikeRio","Brasil"),
    ("gustavo.mendes","BikeRio","Brasil"),("matheus.souza","BikeRio","Brasil"),
    ("jonathan.lins","BikeRio","Brasil"),("hildeberto.lima","BikeRio","Brasil"),
    ("vinicius.nascimento","BikeRio","Brasil"),("alex.severiano","BikeRio","Brasil"),
    ("cassio.souza","BikeRio","Brasil"),("eduardo.teixeira","BikeRio","Brasil"),
    ("juarez.silva","BikePE","Brasil"),("rosenildo.hora","BikeSSA","Brasil"),
    ("rafael.mendonca","BikeRio","Brasil"),("hildebrando.vieira","BikeRio","Brasil"),
    ("bruno.oliveira","BikePE","Brasil"),("pedro.hsilva","BikePE","Brasil"),
    ("evandro.sousa","BikeRio","Brasil"),("silvano.silva","BikeRio","Brasil"),
    ("rodrigo.aguiar","BikeRio","Brasil"),("wellington.sgoncalves","BikeRio","Brasil"),
    ("alexandre.nascimento","BikeRio","Brasil"),("felippe.machado","BikePoa","Brasil"),
    ("marcio.wasen","BikePoa","Brasil"),("jose.fonseca","BikeSSA","Brasil"),
    ("ana.menezes","Corporativo","Brasil"),("nilson.sodre","BikeRio","Brasil"),
    ("erica.prudencio","BikeRio","Brasil"),("bruno.carvalho","Corporativo","Brasil"),
    ("tiago.tomita","Corporativo","Brasil"),("vagner.araujo","BikeRio","Brasil"),
    ("joao.reis","BikeRio","Brasil"),("andre.mendes","BikeSSA","Brasil"),
    ("fernando.carvalho","BikeRio","Brasil"),("sheila.barbosa","Corporativo","Brasil"),
    ("vinicius.qsilva","BikeRio","Brasil"),("tiago.almeida","BikeRio","Brasil"),
    ("anderson.araujo","BikeRio","Brasil"),("rian.basilio","BikeRio","Brasil"),
    ("samuel.bezerra","BikePE","Brasil"),("douglas.junior","BikePE","Brasil"),
    ("antonio.atanasio","BikeRio","Brasil"),("thiago.oliveira","BikeRio","Brasil"),
    ("fabio.silva","BikeRio","Brasil"),("fernanda.marques","Corporativo","Brasil"),
    ("rodrigo.henrique","BikePE","Brasil"),("paulo.sousa","BikeBSB","Brasil"),
    ("charles.xavier","BikeSSA","Brasil"),("vagner.silva","BikeRio","Brasil"),
    ("lucas.costa","BikeRio","Brasil"),("paulo.lima","BikeRio","Brasil"),
    ("ygor.santos","BikeRio","Brasil"),("rodrigo.santos","Corporativo","Brasil"),
    ("icaro.izabel","BikeSSA","Brasil"),("mauricio.maximo","BikeSSA","Brasil"),
    ("luiz.santana","BikeRio","Brasil"),("alan.jesus","BikePE","Brasil"),
    ("emerson.pereira","BikeRio","Brasil"),("regivelton.silva","BikeRio","Brasil"),
    ("maria.santos","BikePE","Brasil"),("marcelo.gomes","BikeRio","Brasil"),
    ("rodrigo.cruz","Corporativo","Brasil"),("magnum.bispo","BikeRio","Brasil"),
    ("roniel.oliveira","BikeBSB","Brasil"),("jaciara.silva","BikePE","Brasil"),
    ("bruna.pinheiro","BikeRio","Brasil"),("flavia.gomes","BikeRio","Brasil"),
    ("keila.santos","BikeRio","Brasil"),("leonardo.mezetti","BikePoa","Brasil"),
    ("jhoni.coelho","BikeRio","Brasil"),("lino.andrade","BikePE","Brasil"),
    ("larissa.souza","Corporativo","Brasil"),("fagner.oliveira","BikeRio","Brasil"),
    ("janilso.ribeiro","BikeRio","Brasil"),("eduardo.lourenco","BikeSSA","Brasil"),
    ("wanderson.felinto","BikeRio","Brasil"),("alex.oliveira","BikeRio","Brasil"),
    ("ana.egito","Corporativo","Brasil"),("camila.luz","Corporativo","Brasil"),
    ("everton.silva","Corporativo","Brasil"),("alef.alves","BikeRio","Brasil"),
    ("tiago.osilva","BikeRio","Brasil"),("carolina.nilo","BikeRio","Brasil"),
    ("fabio.cruz","BikeRio","Brasil"),("marcelo.teixeira","BikeRio","Brasil"),
    ("wanderson.garcia","BikeBSB","Brasil"),("elaine.silva","Corporativo","Brasil"),
    ("paula.oliveira","Corporativo","Brasil"),("uoshington.silva","BikeRio","Brasil"),
    ("cassio.junior","BikePE","Brasil"),("cesar.souza","BikeRio","Brasil"),
    ("janio.silva","BikePE","Brasil"),("maicon.mesquita","BikeRio","Brasil"),
    ("raphael.carvalho","BikeRio","Brasil"),("eliel.costa","BikePE","Brasil"),
    ("diogo.costa","BikeRio","Brasil"),("roger.silva","BikeRio","Brasil"),
    ("douglas.freitas","BikeRio","Brasil"),("bruno.colivera","BikeRio","Brasil"),
    ("thiago.santos","BikeRio","Brasil"),("raphael.cavalcante","BikeBSB","Brasil"),
    ("elton.fernandes","BikeRio","Brasil"),("lucas.pereira","BikeRio","Brasil"),
    ("rodrigo.monteiro","BikeRio","Brasil"),("robert.fernandes","BikeRio","Brasil"),
    ("yan.barbosa","BikeRio","Brasil"),("felipe.cruver","BikeRio","Brasil"),
    ("urvelis.rodriguez","BikeRio","Brasil"),("joao.castelo","BikeRio","Brasil"),
    ("layrrane.xavier","Corporativo","Brasil"),("hiolita.mattiuzzi","BikeCuritiba","Brasil"),
    ("douglas.pereira","BikeCuritiba","Brasil"),("angelo.almeida","BikeRio","Brasil"),
    ("marcio.fernandes","BikeRio","Brasil"),("nathalia.paes","Corporativo","Brasil"),
    ("gabrielle.faria","Corporativo","Brasil"),("yasmim.leao","Corporativo","Brasil"),
    ("priscila.pascoal","Corporativo","Brasil"),("jose.ferreira","BikePE","Brasil"),
    ("andrea.moreno","BikeRio","Brasil"),("akacio.santos","BikePE","Brasil"),
    ("carlos.henrique","BikePE","Brasil"),("wellerson.valandro","BikePoa","Brasil"),
    ("anderson.verissimo","BikeRio","Brasil"),("thiago.mohr","BikeCuritiba","Brasil"),
    ("bruno.assis","BikeFloripa","Brasil"),("luiz.velozo","BikeCuritiba","Brasil"),
    ("giovanni.castelletti","BikeFloripa","Brasil"),("yoswual.serrano","BikeRio","Brasil"),
    ("aline.oliveira","BikeFloripa","Brasil"),("samira.franco","BikeCuritiba","Brasil"),
    ("gustavo.franca","BikeRio","Brasil"),("simone.oliveira","BikeRio","Brasil"),
    ("alexsandro.silva","BikeSSA","Brasil"),("wellington.lopes","BikeCuritiba","Brasil"),
    ("gilson.ribeiro","BikeSSA","Brasil"),("christian.estanga","BikeRio","Brasil"),
    ("deborah.diniz","BikeFloripa","Brasil"),("julio.campos","BikeBH","Brasil"),
    ("leonardo.bpereira","BikePoa","Brasil"),("francilio.silva","BikeRio","Brasil"),
    ("messias.silva","BikeBH","Brasil"),("lucas.ssouza","BikeFloripa","Brasil"),
    ("danilo.farias","BikeRio","Brasil"),("marcelo.sousa","BikeRio","Brasil"),
    ("ivan.albuquerque","BikeRio","Brasil"),("chaeane.taisses","BikePoa","Brasil"),
    ("alexia.bezerra","BikeRio","Brasil"),("ravel.silva","BikeRio","Brasil"),
    ("omar.martinez","BikeRio","Brasil"),("emerson.costa","BikeRio","Brasil"),
    ("fernando.novais","BikeSSA","Brasil"),("jean.silva","BikePoa","Brasil"),
    ("bruno.pereira","BikeRio","Brasil"),("gleyson.sousa","BikeRio","Brasil"),
    ("wagner.krauspenhar","BikePoa","Brasil"),("gabriel.pessoa","BikeSSA","Brasil"),
    ("anatalio.santos","BikeRio","Brasil"),("alexander.pinheiro","BikeRio","Brasil"),
    ("katriel.silva","BikeRio","Brasil"),("fernando.monteiro","BikeRio","Brasil"),
    ("bruno.campos","BikeBH","Brasil"),("janaina.albuquerque","BikePE","Brasil"),
    ("marcos.medeiros","BikeRio","Brasil"),("davi.barbosa","BikeRio","Brasil"),
    ("fernanda.aguiar","BikeRio","Brasil"),("arthur.bsilva","BikePE","Brasil"),
    ("andrea.silva","BikeRio","Brasil"),("maciel.bezerra","BikeRio","Brasil"),
    ("rennan.queiroz1","BikeRio","Brasil"),("jose.deguchi","BikeCuritiba","Brasil"),
    ("luiz.sbarros","BikeRio","Brasil"),("douglas.asilva","BikeRio","Brasil"),
    ("lucas.nunes","BikePoa","Brasil"),("raphael.mancebo","BikeRio","Brasil"),
    ("lucas.kozowiski","BikeCuritiba","Brasil"),("eduardo.andrade","BikeFloripa","Brasil"),
    ("alan.conceicao","BikeSSA","Brasil"),("vinicius.chalef","BikeRio","Brasil"),
    ("diorgenes.souza","BikeRio","Brasil"),("cayo.garcia","BikeRio","Brasil"),
    ("felipe.scosta","BikeRio","Brasil"),("lorestin.souza","BikeRio","Brasil"),
    ("bruno.guilherme","BikeRio","Brasil"),("assuero.santos","BikePE","Brasil"),
    ("vander.souza","BikeRio","Brasil"),("wellington.cunha","BikeRio","Brasil"),
    ("larissa.soares","BikeRio","Brasil"),("larissa.mattos","BikeRio","Brasil"),
    ("andre.prestes","BikeCuritiba","Brasil"),("danielle.silva","BikePE","Brasil"),
    ("jose.asantos","BikeSSA","Brasil"),("thiago.steixeira","BikeSSA","Brasil"),
    ("vinicius.basilio","BikeRio","Brasil"),("lucas.gteixeira","BikeRio","Brasil"),
    ("rodrigo.eskenazi","BikeRio","Brasil"),("ronielle.carvalho","BikeRio","Brasil"),
    ("derick.borges","BikeRio","Brasil"),("thassio.leite","BikeRio","Brasil"),
    ("julio.goivaes","BikeRio","Brasil"),("wallace.carneiro","Corporativo","Brasil"),
    ("leoneir.martins","BikeRio","Brasil"),("ramon.oliveira","BikeRio","Brasil"),
    ("francisco.filho","BikeRio","Brasil"),("marcelo.lima","BikeRio","Brasil"),
    ("george.magalhaes","BikeRio","Brasil"),("jacson.fernandes","BikeFloripa","Brasil"),
    ("carlos.rodrigues","BikeRio","Brasil"),("raphael.lacerda","BikeBSB","Brasil"),
    ("luiz.marques","BikeRio","Brasil"),("joao.miguel","BikeFloripa","Brasil"),
    ("roberto.paula","BikeFloripa","Brasil"),("humberto.lopes","BikeSSA","Brasil"),
    ("adam.silva","BikeRio","Brasil"),("anderson.rodrigues","BikeSSA","Brasil"),
    ("joao.cardoso","BikeRio","Brasil"),("maria.silva","BikeRio","Brasil"),
    ("jeisson.gordillo","BikeRio","Brasil"),("emerson.jesus","BikeRio","Brasil"),
    ("davidson.filho","BikeRio","Brasil"),("wagner.silva","BikeRio","Brasil"),
    ("alexander.soares","BikeRio","Brasil"),("daniel.ssilva","BikeBH","Brasil"),
    ("victor.miranda","BikeRio","Brasil"),("sidney.junior","BikeCuritiba","Brasil"),
    ("higor.couto","BikeCuritiba","Brasil"),("charles.rosa","BikePoa","Brasil"),
    ("jhonnatan.bonfim","BikeRio","Brasil"),("pedro.miranda","BikeBH","Brasil"),
    ("alan.alves","BikeBH","Brasil"),("rafael.lacerda","BikeBSB","Brasil"),
    ("kethlen.faria","BikeRio","Brasil"),("leandro.lucio","BikeRio","Brasil"),
    ("bruno.machado","BikeRio","Brasil"),("wilian.junior","BikeRio","Brasil"),
    ("paulo.almeida","BikeSSA","Brasil"),("samir.macedo","BikeFloripa","Brasil"),
    ("lucas.goes","BikeSSA","Brasil"),("artur.vargas","BikePoa","Brasil"),
    ("brayan.yanez","BikePoa","Brasil"),("israel.filho","BikeSSA","Brasil"),
    ("ana.campiglia","BikeRio","Brasil"),("joseane.silva","BikeBSB","Brasil"),
    ("eduardo.oliveira","BikePoa","Brasil"),("fernanda.rosa","BikePoa","Brasil"),
    ("sergio.oliveira","BikePE","Brasil"),("patrick.moro","BikePoa","Brasil"),
    ("felipe.rcarvalho","BikeBSB","Brasil"),("kaue.krum","BikeCuritiba","Brasil"),
    ("tereza.morais","BikeRio","Brasil"),("carlos.bezerra","BikeSSA","Brasil"),
    ("fernanda.araujo","BikeSSA","Brasil"),("wellington.paim","BikeSSA","Brasil"),
    ("lazaro.santos","BikeSSA","Brasil"),("kiaku.nkunga","BikeRio","Brasil"),
    ("carlos.peche","BikeRio","Brasil"),("marcia.lucena","BikeBSB","Brasil"),
    ("sarah.silva","BikeRio","Brasil"),("ismael.silva","BikePoa","Brasil"),
    ("laos.rosa","BikePoa","Brasil"),("emerson.santos","BikeBH","Brasil"),
    ("daniel.martins","BikeRio","Brasil"),("italo.nuno","BikeSSA","Brasil"),
    ("edgar.dias","BikeBH","Brasil"),("anderson.anjos","BikeSSA","Brasil"),
    ("cesar.marquez","BikeBSB","Brasil"),("lucas.cabral","BikeBH","Brasil"),
    ("fabio.teixeira","BikeRio","Brasil"),("bruno.brito","BikeSSA","Brasil"),
    ("anderson.barreto","BikeSSA","Brasil"),("jairo.souza","BikeRio","Brasil"),
    ("wallas.santos","BikeSSA","Brasil"),("darliany.souza","BikeBSB","Brasil"),
    ("elves.silva","BikePE","Brasil"),("juliano.linhares","BikePoa","Brasil"),
    ("eduardo.cunha","BikePE","Brasil"),("marcel.silva","BikePE","Brasil"),
    ("lucas.soares","BikeSSA","Brasil"),("caique.almeida","BikeSSA","Brasil"),
    ("guilherme.osilva","BikeRio","Brasil"),("thalyta.silva","BikePE","Brasil"),
    ("kenya.costa","BikePoa","Brasil"),("erico.oliveira","BikeFloripa","Brasil"),
    ("maira.neisenger","BikeFloripa","Brasil"),("wesley.santos","BikePE","Brasil"),
    ("junio.hypolito","BikeBH","Brasil"),("bruna.santos","BikeSSA","Brasil"),
    ("edimeia.jesus","BikeSSA","Brasil"),("luis.santos","BikeSSA","Brasil"),
    ("ricardo.teixeira","BikeRio","Brasil"),("renan.andrade","BikeRio","Brasil"),
    ("fabio.franca","BikeRio","Brasil"),("julia.pires","BikeRio","Brasil"),
    ("leandro.souza","BikeRio","Brasil"),("rosa.barbosa","BikeRio","Brasil"),
    ("luiza.almeida","BikeBH","Brasil"),("luiz.eduardo","BikeRio","Brasil"),
    ("emerson.souza","Corporativo","Brasil"),("evaldo.lima","BikeRio","Brasil"),
    ("victor.teixeira","BikeRio","Brasil"),("tallita.marques","BikeRio","Brasil"),
    ("dionatan.premibida","BikeCuritiba","Brasil"),("pedro.almeida","BikeRio","Brasil"),
    ("gilmar.junior","BikeRio","Brasil"),("washington.felix","BikeBH","Brasil"),
    ("ricardo.sodre","BikeSSA","Brasil"),("lucas.cardoso","BikeRio","Brasil"),
    ("elias.santos","BikeRio","Brasil"),("welbert.souza","BikeRio","Brasil"),
    ("carla.bezerra","BikeRio","Brasil"),("marcio.silva","BikeRio","Brasil"),
    ("darcio.junior","BikeBH","Brasil"),("victor.jorge","BikeRio","Brasil"),
    ("isabela.duarte","BikeRio","Brasil"),("marcio.carvalho","BikeRio","Brasil"),
    ("pedro.moehleck","BikeRio","Brasil"),("jociel.pereira","BikeSSA","Brasil"),
    ("alexandre.fonseca","BikeRio","Brasil"),("anderson.paulo","BikeRio","Brasil"),
    ("savio.caldeira","BikeBH","Brasil"),("moacir.junior","BikeRio","Brasil"),
    ("lucas.valenca","BikeFloripa","Brasil"),("leandro.pires","BikeFloripa","Brasil"),
    ("caique.santos","BikeBH","Brasil"),("joao.cintra","BikeBH","Brasil"),
    ("thiago.osantos","BikePoa","Brasil"),("moises.gomes","BikeRio","Brasil"),
    ("eder.costa","BikeCuritiba","Brasil"),("luiz.pereira","BikeBSB","Brasil"),
    ("paulo.sergio","BikeSSA","Brasil"),("thalles.silva","BikeRio","Brasil"),
    ("omar.aguilera","BikeFloripa","Brasil"),("gabriel.siqueira","BikePoa","Brasil"),
    ("marcos.oliveira","BikeRio","Brasil"),("jhonatan.costa","BikeRio","Brasil"),
    ("vinicius.ribeiro","BikeRio","Brasil"),("carlos.eduardo","BikeRio","Brasil"),
    ("carlos.freitas","BikePoa","Brasil"),("guilherme.vaz","BikePoa","Brasil"),
    ("cleyton.silva","BikeRio","Brasil"),("eduardo.sebastiao","BikeBH","Brasil"),
    ("vinicius.fernandes","BikeRio","Brasil"),("jonathan.avelino","BikeRio","Brasil"),
    ("paulo.lopes","BikeBH","Brasil"),("brendo.alcantara","BikeBSB","Brasil"),
    ("regis.silva","BikePoa","Brasil"),("leonardo.mendes","BikePoa","Brasil"),
    ("gerson.cabral","BikeRio","Brasil"),("wagner.machado","BikeFloripa","Brasil"),
    ("alexsandro.weretycki","BikeCuritiba","Brasil"),("mariana.sousa","BikeRio","Brasil"),
    ("marcon.deus","BikeRio","Brasil"),("filipe.medrado","BikeSSA","Brasil"),
    ("ibson.allendes","BikeRio","Brasil"),("vitoria.safadi","BikeRio","Brasil"),
    ("luan.moura","BikeRio","Brasil"),("josue.almeida","BikeRio","Brasil"),
    ("denis.silva","BikeRio","Brasil"),("michael.alves","BikeRio","Brasil"),
    ("maria.siqueira","BikeRio","Brasil"),("paloma.silva","Corporativo","Brasil"),
    ("gabriel.souza","BikeRio","Brasil"),("marco.braz","BikeRio","Brasil"),
    ("matheus.rocha","BikeRio","Brasil"),("sergio.gomes","BikeRio","Brasil"),
    ("lincoln.fernandes","BikeRio","Brasil"),("pedro.kronitzky","BikePoa","Brasil"),
    ("anderson.oliveira","BikeRio","Brasil"),("luis.gomes","BikeRio","Brasil"),
    ("jediel.silva","BikeSampa","Brasil"),("gislandia.cardoso","BikeSampa","Brasil"),
    ("damiao.santana","CD Extrema","Brasil"),("ana.martins","CD Extrema","Brasil"),
    ("hector.bolivar","CD Extrema","Brasil"),("wesley.herculano","CD Extrema","Brasil"),
    ("everton.dias","CD Extrema","Brasil"),("maurilio.junior","CD Extrema","Brasil"),
    ("leia.grecco","CD Extrema","Brasil"),("cesar.siso","CD Extrema","Brasil"),
    ("natalia.ronchi","BAEcobici","Argentina"),("castano.rodriguez","BAEcobici","Argentina"),
    ("gabriel.sorace","BAEcobici","Argentina"),("hector.quiroga","BAEcobici","Argentina"),
    ("cristian.cordova","BAEcobici","Argentina"),("jonatan.barrientos","BAEcobici","Argentina"),
    ("martin.diaz","BAEcobici","Argentina"),("sebastian.frattura","BAEcobici","Argentina"),
    ("pablo.lopez","BAEcobici","Argentina"),("henry.gisbert","BAEcobici","Argentina"),
    ("richar.riveros","BAEcobici","Argentina"),("ignacio.romero","BAEcobici","Argentina"),
    ("diego.tello","BAEcobici","Argentina"),("tamara.szydlowski","BAEcobici","Argentina"),
    ("marian.dapueto","BAEcobici","Argentina"),("luciano.varela","BAEcobici","Argentina"),
    ("leticia.torres","BAEcobici","Argentina"),("jessica.suarez","BAEcobici","Argentina"),
    ("ezequiel.escalante","BAEcobici","Argentina"),("jose.molina","BAEcobici","Argentina"),
    ("manuel.mansilla","BAEcobici","Argentina"),("gabriel.pino","BAEcobici","Argentina"),
    ("jonatan.carabajal","BAEcobici","Argentina"),("mario.rojas","BAEcobici","Argentina"),
    ("celeste.persuh","BAEcobici","Argentina"),("claudio.arguello","BAEcobici","Argentina"),
    ("roberto.medori","BAEcobici","Argentina"),("eduardo.guzman","BAEcobici","Argentina"),
    ("joam.galea","BAEcobici","Argentina"),("jonathan.gonzalez","BAEcobici","Argentina"),
    ("hector.zeballos","BAEcobici","Argentina"),("aldana.buendia","BAEcobici","Argentina"),
    ("julian.prado","BAEcobici","Argentina"),("gonzalo.ferreyra","BAEcobici","Argentina"),
    ("diego.paredes","BAEcobici","Argentina"),("erick.marcano","BAEcobici","Argentina"),
    ("walter.sorella","BAEcobici","Argentina"),("leonardo.dominguez","BAEcobici","Argentina"),
    ("roman.marek","BAEcobici","Argentina"),("romualdo.toconas","BAEcobici","Argentina"),
    ("javier.orellano","BAEcobici","Argentina"),("jose.martinez","BAEcobici","Argentina"),
    ("milton.velardes","BAEcobici","Argentina"),("ruben.gonzalez","BAEcobici","Argentina"),
    ("lucas.pollet","BAEcobici","Argentina"),("lucas.caceres","BAEcobici","Argentina"),
    ("jose.sanchez","BAEcobici","Argentina"),("emanuel.perez","BAEcobici","Argentina"),
    ("pablo.boyer","BAEcobici","Argentina"),("julio.carabajal","BAEcobici","Argentina"),
    ("diego.moreno","BAEcobici","Argentina"),("laila.slavutzky","BAEcobici","Argentina"),
    ("luciano.escalante","BAEcobici","Argentina"),("nicolas.yanicelli","BAEcobici","Argentina"),
    ("juan.gavilan","BAEcobici","Argentina"),("armando.arias","BAEcobici","Argentina"),
    ("braian.vassia","BAEcobici","Argentina"),("diego.iluchko","BAEcobici","Argentina"),
    ("ligotti.adrian","BAEcobici","Argentina"),("alejandro.castillo","BAEcobici","Argentina"),
    ("brian.vicenzo","BAEcobici","Argentina"),("godoy.segundo","BAEcobici","Argentina"),
    ("nahuel.di","BAEcobici","Argentina"),("jesica.ferrer","BAEcobici","Argentina"),
    ("julieta.rey","BAEcobici","Argentina"),("castillo.maximiliano","BAEcobici","Argentina"),
    ("mauricio.silvero","BAEcobici","Argentina"),("franco.espejo","BAEcobici","Argentina"),
    ("cintia.grispo","BAEcobici","Argentina"),("edson.calle","BAEcobici","Argentina"),
    ("antonio.ezequiel","BAEcobici","Argentina"),("gonzalo.risso","BAEcobici","Argentina"),
    ("diego.alvarenque","BAEcobici","Argentina"),("mayer.damian","BAEcobici","Argentina"),
    ("zotelo.agustin","BAEcobici","Argentina"),("jesica.zanabria","BAEcobici","Argentina"),
    ("silvana.jaimez","BAEcobici","Argentina"),("julian.cevey","BAEcobici","Argentina"),
    ("ibanes.emanuel","BAEcobici","Argentina"),("lucas.godoy","BAEcobici","Argentina"),
    ("joaquin.benitez","BAEcobici","Argentina"),("asael.federico","BAEcobici","Argentina"),
    ("micaela.castano","BAEcobici","Argentina"),("barbara.fagnani","BAEcobici","Argentina"),
    ("thiago.rodriguez","BAEcobici","Argentina"),("sabrina.ortellado","BAEcobici","Argentina"),
    ("thiago.quiroz","BAEcobici","Argentina"),("iago.riveiro","BAEcobici","Argentina"),
    ("andres.cardozo","BAEcobici","Argentina"),("anthony.stivens","BAEcobici","Argentina"),
    ("edgar.aguero","BAEcobici","Argentina"),("milena.oviedo","BAEcobici","Argentina"),
    ("valentina.almentero","BAEcobici","Argentina"),("lucas.omil","BAEcobici","Argentina"),
    ("nicolas.leiva","BAEcobici","Argentina"),("sofia.simiele","BAEcobici","Argentina"),
    ("ignacio.herrera","BAEcobici","Argentina"),("yonatan.sales","BAEcobici","Argentina"),
    ("alan.quinas","BAEcobici","Argentina"),("nataly.rodriguez","BAEcobici","Argentina"),
    ("leonardo.kowalczuk","BAEcobici","Argentina"),("julian.gonzalez","BAEcobici","Argentina"),
    ("marcos.fernandez","BAEcobici","Argentina"),("mario.romeo","BAEcobici","Argentina"),
    ("franco.gonzalez","BAEcobici","Argentina"),("franco.girard","BAEcobici","Argentina"),
    ("javiera.pinto","BikeSantiago","Chile"),("matias.barros","BikeSantiago","Chile"),
    ("felipe.ruiz","BikeSantiago","Chile"),("jose.espinoza","BikeSantiago","Chile"),
    ("alexander.valderrama","BikeSantiago","Chile"),("alejandra.donoso","BikeSantiago","Chile"),
    ("christian.cerda","BikeSantiago","Chile"),("alexander.acosta","BikeSantiago","Chile"),
    ("rebeca.paredes","BikeSantiago","Chile"),("luis.gonzalez","BikeSantiago","Chile"),
    ("matteo.vergara","BikeSantiago","Chile"),("ednailton.souza","BikeSantiago","Chile"),
    ("bastian.caceres","BikeSantiago","Chile"),("raul.reyes","BikeSantiago","Chile"),
    ("daniela.izquierdo","BikeSantiago","Chile"),("michell.soriano","BikeSantiago","Chile"),
    ("yohana.navarro","BikeSantiago","Chile"),("cristian.soto","BikeSantiago","Chile"),
    ("claudia.toro","BikeSantiago","Chile"),("miguel.monroy","BikeSantiago","Chile"),
    ("ximena.barrera","BikeSantiago","Chile"),("allan.loyola","BikeSantiago","Chile"),
    ("fernando.herrera","BikeSantiago","Chile"),("carlos.regular","BikeSantiago","Chile"),
    ("mauricio.henriquez","BikeSantiago","Chile"),("joshua.perez","BikeSantiago","Chile"),
    ("felipe.salazar","BikeSantiago","Chile"),("joaquin.gonzalez","BikeSantiago","Chile"),
    ("leonardo.pinilla","BikeSantiago","Chile"),("jonathan.nunez","BikeSantiago","Chile"),
    ("enmanuel.garcia","BikeSantiago","Chile"),("alexander.bustos","BikeSantiago","Chile"),
    ("victoria.pericana","BikeSantiago","Chile"),("inti.flores","BikeSantiago","Chile"),
    ("daniel.navarrete","BikeSantiago","Chile"),("matias.figueroa","BikeSantiago","Chile"),
    ("eduardo.caceres","BikeSantiago","Chile"),("jorge.escobar","BikeSantiago","Chile"),
    ("cristobal.castillo","BikeSantiago","Chile"),("jorge.ferraro","BikeSantiago","Chile"),
    ("christopher.lineros","BikeSantiago","Chile"),
    ("camila.acosta","BikeBogota","Colômbia"),("jhoan.hurtado","BikeBogota","Colômbia"),
    ("jeison.reyes","BikeBogota","Colômbia"),("july.velasco","BikeBogota","Colômbia"),
    ("andres.amador","BikeBogota","Colômbia"),("juan.ortiz","BikeBogota","Colômbia"),
    ("carolina.rodriguez","BikeBogota","Colômbia"),("leidy.torres","BikeBogota","Colômbia"),
    ("kevin.pineda","BikeBogota","Colômbia"),("liz.ussa","BikeBogota","Colômbia"),
    ("paola.ladino","BikeBogota","Colômbia"),("diana.aranda","BikeBogota","Colômbia"),
    ("angie.reina","BikeBogota","Colômbia"),("oscar.rodriguez","BikeBogota","Colômbia"),
    ("janner.garcia","BikeBogota","Colômbia"),("laura.vasquez","BikeBogota","Colômbia"),
    ("oscar.rojas","BikeBogota","Colômbia"),("luisa.restrepo","BikeBogota","Colômbia"),
]

USER_MAP = {}
for h, p, c in USERS_RAW:
    key = h.strip().lower()
    praca = "BikeSampa" if p.strip().lower() == "riviera" else p.strip()
    USER_MAP[key] = {"praca": praca, "pais": c.strip()}

def build_output(raw):
    standings = raw.get("standings", [])
    finished = raw.get("finishedMatches", [])
    enriched, unmatched = [], []
    for e in standings:
        u = e.get("user", {})
        handle = (u.get("handle") or "").strip().lower()
        info = USER_MAP.get(handle)
        if not info:
            unmatched.append(handle)
            info = {"praca": "Outros", "pais": "Outros"}
        enriched.append({
            "rank": e.get("rank"),
            "totalPoints": e.get("totalPoints", 0),
            "prevPosition": e.get("prevPosition", 0),
            "prevTotalPoints": e.get("prevTotalPoints", 0),
            "predictionsCount": e.get("predictionsCount", 0),
            "exactScoreCount": e.get("exactScoreCount", 0),
            "correctWinnerCount": e.get("correctWinnerCount", 0),
            "handle": handle,
            "displayName": u.get("displayName", handle),
            "praca": info["praca"],
            "pais": info["pais"],
        })
    return {
        "updatedAt": datetime.utcnow().isoformat() + "Z",
        "finishedMatchesCount": len(finished),
        "standings": enriched,
        "unmatchedHandles": unmatched
    }

if __name__ == "__main__":
    print("Renovando JWT...")
    jwt = get_fresh_jwt()
    print("Buscando leaderboard...")
    raw = fetch_leaderboard(jwt)
    output = build_output(raw)
    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    n = len(output["standings"])
    j = output["finishedMatchesCount"]
    print(f"OK — {n} participantes, {j} jogos encerrados")
    if output["unmatchedHandles"]:
        print(f"Sem match: {output['unmatchedHandles']}")
