import requests, json, os
from datetime import datetime

FIREBASE_REFRESH_TOKEN = os.environ.get("FIREBASE_REFRESH_TOKEN")
FIREBASE_API_KEY = os.environ.get("FIREBASE_API_KEY")
GROUP_CODE = "F3XVPHFW"

def get_fresh_jwt():
    url = f"https://securetoken.googleapis.com/v1/token?key={FIREBASE_API_KEY}"
    r = requests.post(url, json={"grant_type":"refresh_token","refresh_token":FIREBASE_REFRESH_TOKEN}, timeout=15)
    r.raise_for_status()
    return r.json()["id_token"]

def fetch_leaderboard(jwt):
    url = f"https://api.dacopa.com/groups/{GROUP_CODE}/leaderboard"
    headers = {
        "Authorization": f"Bearer {jwt}",
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Origin": "https://app.dacopa.com",
        "X-Client-Capabilities": "predictions-v2"
    }
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    return r.json()

# handle -> (praca, pais, diretoria, adm_corp)
USERS_RAW = [
    ("gabriela.gomes","Corporativo","Brasil","B2B","Corporativo"),
    ("tomas.martins","Corporativo","Brasil","CEO","Corporativo"),
    ("joyce.vasconcelos","Corporativo","Brasil","CFO","Corporativo"),
    ("amanda.dias","Corporativo","Brasil","CFO","Corporativo"),
    ("filipe.faleiro","Corporativo","Brasil","B2B","Corporativo"),
    ("carolina.villa","Corporativo","Brasil","CTIO","Corporativo"),
    ("andre.marasco","Corporativo","Brasil","CTIO","Corporativo"),
    ("gustavo.guedez","Corporativo","Brasil","CBO","Corporativo"),
    ("jose.silva","BikeSampa","Brasil","CBO","Operação"),
    ("mauro.rodrigues","BikeSampa","Brasil","CBO","Operação"),
    ("sandro.santos","BikeSampa","Brasil","CBO","Operação"),
    ("wellington.cavalcante","BikeSampa","Brasil","CBO","Operação"),
    ("johnny.cana","BikeSampa","Brasil","CBO","Operação"),
    ("hernani.silva","BikeSampa","Brasil","CBO","Operação"),
    ("tadeu.junior","BikeSampa","Brasil","CBO","Operação"),
    ("marcos.cardoso","BikeSampa","Brasil","CBO","Operação"),
    ("sabrina.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("vinicius.arruda","BikeSampa","Brasil","CBO","Operação"),
    ("felipe.asantos","BikeSampa","Brasil","CBO","Operação"),
    ("vinicius.figueiredo","BikeSampa","Brasil","CBO","Operação"),
    ("jhonattan.francisco","BikeSampa","Brasil","CBO","Operação"),
    ("natalia.giordani","Corporativo","Brasil","CTIO","Corporativo"),
    ("raul.sousa","BikeSampa","Brasil","CBO","Operação"),
    ("alice.waquil","Corporativo","Brasil","CTIO","Corporativo"),
    ("andre.bifulco","Corporativo","Brasil","CFO","Corporativo"),
    ("valquiria.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("antonio.ferreira","Corporativo","Brasil","CTIO","Corporativo"),
    ("debora.oliveira","Corporativo","Brasil","CTIO","Corporativo"),
    ("shirleide.martins","Corporativo","Brasil","CBO","Corporativo"),
    ("eduardo.lima","BikeSampa","Brasil","CBO","Operação"),
    ("rafael.bento","BikeSampa","Brasil","CBO","Operação"),
    ("thailane.sacerdote","Corporativo","Brasil","CBO","Corporativo"),
    ("ariane.pina","Corporativo","Brasil","CBO","Corporativo"),
    ("flavio.pangracio","Corporativo","Brasil","CTIO","Corporativo"),
    ("gabriel.dacome","BikeSampa","Brasil","CBO","Operação"),
    ("sthefany.simioni","Corporativo","Brasil","RELGOV","Corporativo"),
    ("gustavo.torquato","Corporativo","Brasil","CTIO","Corporativo"),
    ("yago.caetano","Corporativo","Brasil","CTIO","Corporativo"),
    ("michelle.silva","BikeSampa","Brasil","CBO","Operação"),
    ("luana.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("fernando.fernandes","Corporativo","Brasil","CTIO","Corporativo"),
    ("alexandro.pereda","BikeSampa","Brasil","CBO","Operação"),
    ("cleriston.santos","BikeSampa","Brasil","CBO","Operação"),
    ("marcos.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("natalia.cunha","Corporativo","Brasil","CBO","Corporativo"),
    ("paulo.freitas","Corporativo","Brasil","CFO","Corporativo"),
    ("victor.dantas","Corporativo","Brasil","CBO","Corporativo"),
    ("wellington.soares","Corporativo","Brasil","CTIO","Corporativo"),
    ("kelvis.rojas","BikeSampa","Brasil","CBO","Operação"),
    ("mario.araujo","Corporativo","Brasil","CTIO","Corporativo"),
    ("vinicius.pires","Corporativo","Brasil","CBO","Corporativo"),
    ("olivia.mitne","Corporativo","Brasil","CEO","Corporativo"),
    ("alex.souza","BikeSampa","Brasil","CBO","Operação"),
    ("gabriela.silva","Corporativo","Brasil","CFO","Corporativo"),
    ("ulisses.oliveira","Corporativo","Brasil","CFO","Corporativo"),
    ("yasmin.goncalves","Corporativo","Brasil","CBO","Corporativo"),
    ("caroline.nascimento","Corporativo","Brasil","CBO","Corporativo"),
    ("julia.jesus","Corporativo","Brasil","CBO","Corporativo"),
    ("gabriel.lopes","Corporativo","Brasil","CTIO","Corporativo"),
    ("luiza.lopes","Corporativo","Brasil","CBO","Corporativo"),
    ("fabio.pereira","BikeSampa","Brasil","CBO","Operação"),
    ("rui.souza","Corporativo","Brasil","CTIO","Corporativo"),
    ("josue.sombra","BikeSampa","Brasil","CBO","Operação"),
    ("carlos.pereira","BikeSampa","Brasil","CBO","Operação"),
    ("guilherme.baldissera","Corporativo","Brasil","CTIO","Corporativo"),
    ("wesley.marcelino","Corporativo","Brasil","CTIO","Corporativo"),
    ("icaro.uchoa","BikeSampa","Brasil","CBO","Operação"),
    ("roberto.dias","Corporativo","Brasil","CTIO","Corporativo"),
    ("barbara.sousa","BikeSampa","Brasil","CBO","Operação"),
    ("cristovao.pereira","BikeSampa","Brasil","CBO","Operação"),
    ("daniel.aquino","BikeSampa","Brasil","CBO","Operação"),
    ("matheus.vieira","BikeSampa","Brasil","CBO","Operação"),
    ("elayne.armas","BikeSampa","Brasil","CBO","Operação"),
    ("leonardo.braga","BikeSampa","Brasil","CBO","Operação"),
    ("italo.barros","Corporativo","Brasil","CBO","Corporativo"),
    ("mariana.pontel","Corporativo","Brasil","CFO","Corporativo"),
    ("xaiene.silva","BikeSampa","Brasil","CBO","Operação"),
    ("marcos.barreto","Corporativo","Brasil","CBO","Corporativo"),
    ("vitorya.santos","Corporativo","Brasil","CBO","Corporativo"),
    ("alexandre.rosa","Corporativo","Brasil","CEO","Corporativo"),
    ("juliana.miranda","BikeSampa","Brasil","CBO","Operação"),
    ("carlos.roldan","BikeSampa","Brasil","CBO","Operação"),
    ("amanda.leite","BikeSampa","Brasil","CBO","Operação"),
    ("emerson.soares","Corporativo","Brasil","CBO","Corporativo"),
    ("willian.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("julya.silva","Corporativo","Brasil","CFO","Corporativo"),
    ("waldomiro.feitosa","BikeSampa","Brasil","CBO","Operação"),
    ("heitor.piovesan","Corporativo","Brasil","CFO","Corporativo"),
    ("yean.rodriguez","BikeSampa","Brasil","CBO","Operação"),
    ("bruno.martins","Corporativo","Brasil","CTIO","Corporativo"),
    ("sueli.nascimento","Corporativo","Brasil","CBO","Corporativo"),
    ("sirleide.paz","Corporativo","Brasil","CBO","Corporativo"),
    ("victor.falcao","Corporativo","Brasil","CBO","Corporativo"),
    ("thiago.boufelli","Corporativo","Brasil","CEO","Corporativo"),
    ("lizandra.lacerda","Corporativo","Brasil","CFO","Corporativo"),
    ("marcos.santos","Corporativo","Brasil","CFO","Corporativo"),
    ("roberta.jorge","Corporativo","Brasil","CFO","Corporativo"),
    ("bianca.oliveira","Corporativo","Brasil","CBO","Corporativo"),
    ("felipe.rodrigues","BikeSampa","Brasil","CBO","Operação"),
    ("aline.menezes","Corporativo","Brasil","CFO","Corporativo"),
    ("dyego.franciscato","Corporativo","Brasil","CFO","Corporativo"),
    ("matheus.ferreira","BikeSampa","Brasil","CBO","Operação"),
    ("josiene.souza","Corporativo","Brasil","CFO","Corporativo"),
    ("elias.rodriguez","BikeSampa","Brasil","CBO","Operação"),
    ("eloise.tripodi","Corporativo","Brasil","CBO","Corporativo"),
    ("maria.souza","Corporativo","Brasil","CBO","Corporativo"),
    ("vinicius.cassimiro","BikeSampa","Brasil","CBO","Operação"),
    ("leonardo.luz","BikeSampa","Brasil","CBO","Operação"),
    ("wellington.conceicao","BikeSampa","Brasil","CBO","Operação"),
    ("antonio.felipe","Corporativo","Brasil","CTIO","Corporativo"),
    ("paulo.martins","BikeSampa","Brasil","CBO","Operação"),
    ("gabriel.braz","Corporativo","Brasil","CBO","Corporativo"),
    ("tanyfer.oliveira","Corporativo","Brasil","CFO","Corporativo"),
    ("erika.jesus","Corporativo","Brasil","CBO","Corporativo"),
    ("ana.cagnotto","Corporativo","Brasil","CTIO","Corporativo"),
    ("bruno.bezerra","BikeSampa","Brasil","CBO","Operação"),
    ("jade.silva","Corporativo","Brasil","CFO","Corporativo"),
    ("alexsander.goes","BikeSampa","Brasil","CBO","Operação"),
    ("lucas.andrade","BikeSampa","Brasil","CBO","Operação"),
    ("victor.neto","BikeSampa","Brasil","CBO","Operação"),
    ("eduarda.oliveira","Corporativo","Brasil","CFO","Corporativo"),
    ("matheus.alves","BikeSampa","Brasil","CBO","Operação"),
    ("marjorie.morais","BikeSampa","Brasil","CBO","Operação"),
    ("thiago.roque","Corporativo","Brasil","CBO","Corporativo"),
    ("andressa.souza","Corporativo","Brasil","CTIO","Corporativo"),
    ("mauricio.villar","Corporativo","Brasil","CEO","Corporativo"),
    ("eduardo.goncalves","BikeSampa","Brasil","CBO","Operação"),
    ("paulo.andrade","BikeSampa","Brasil","CBO","Operação"),
    ("elisangela.sampaio","Corporativo","Brasil","CFO","Corporativo"),
    ("caio.santos","BikeSampa","Brasil","CBO","Operação"),
    ("jhenifer.silva","Corporativo","Brasil","CTIO","Corporativo"),
    ("joao.pecin","BikeSampa","Brasil","CBO","Operação"),
    ("beatriz.silva","Corporativo","Brasil","CTIO","Corporativo"),
    ("stephane.oliveira","BikeSampa","Brasil","CBO","Operação"),
    ("angelo.dourado","BikeSampa","Brasil","CBO","Operação"),
    ("iris.nunes","BikeSampa","Brasil","CBO","Operação"),
    ("angela.silva","BikeSampa","Brasil","CBO","Operação"),
    ("leonardo.hohne","Corporativo","Brasil","CBO","Corporativo"),
    ("joycy.fernandes","BikeSampa","Brasil","CBO","Operação"),
    ("tatiane.silva","BikeSampa","Brasil","CBO","Operação"),
    ("barbara.fortesa","Corporativo","Brasil","CFO","Corporativo"),
    ("gleicy.oliveira","Corporativo","Brasil","CBO","Corporativo"),
    ("rodrigo.canola","Corporativo","Brasil","CTIO","Corporativo"),
    ("mariana.cardoso","Corporativo","Brasil","B2B","Corporativo"),
    ("cinthia.ramos","BikeSampa","Brasil","CBO","Operação"),
    ("andreza.silva","Corporativo","Brasil","CFO","Corporativo"),
    ("vanessa.santos","Corporativo","Brasil","CTIO","Corporativo"),
    ("julia.lira","Corporativo","Brasil","CBO","Corporativo"),
    ("alan.pereira","Corporativo","Brasil","CTIO","Corporativo"),
    ("vinicius.paula","Corporativo","Brasil","CBO","Corporativo"),
    ("vitor.monteiro","Corporativo","Brasil","CTIO","Corporativo"),
    ("matheus.barbosa","BikeSampa","Brasil","CBO","Operação"),
    ("tiago.soares","Corporativo","Brasil","CBO","Corporativo"),
    ("felipe.fernandes","Corporativo","Brasil","CTIO","Corporativo"),
    ("bianca.andrade","BikeSampa","Brasil","CBO","Operação"),
    ("gustavo.alves","BikeSampa","Brasil","CBO","Operação"),
    ("marina.brondani","Corporativo","Brasil","CTIO","Corporativo"),
    ("andersom.fontoura","BikeSampa","Brasil","CBO","Operação"),
    ("igor.monteiro","BikeSampa","Brasil","CBO","Operação"),
    ("gerson.junior","BikeSampa","Brasil","CBO","Operação"),
    ("lucas.barbosa","BikeSampa","Brasil","CBO","Operação"),
    ("elisangela.corticeiro","BikeSampa","Brasil","CBO","Operação"),
    ("paloma.santos","Corporativo","Brasil","CFO","Corporativo"),
    ("diogo.csilva","BikeSampa","Brasil","CBO","Operação"),
    ("alvaro.santos","BikeSampa","Brasil","CBO","Operação"),
    ("izaque.scomparim","Corporativo","Brasil","CTIO","Corporativo"),
    ("bianca.rodrigues","Corporativo","Brasil","CFO","Corporativo"),
    ("lucas.snascimento","BikeSampa","Brasil","CBO","Operação"),
    ("henrique.maitan","Corporativo","Brasil","CTIO","Corporativo"),
    ("gabriel.nascimento","Corporativo","Brasil","CTIO","Corporativo"),
    ("pablo.nascimento","Corporativo","Brasil","CTIO","Corporativo"),
    ("higor.carvalho","BikeSampa","Brasil","CBO","Operação"),
    ("afonso.felippe","BikeSampa","Brasil","CBO","Operação"),
    ("rafaella.silbermann","Corporativo","Brasil","B2B","Corporativo"),
    ("caio.lima","BikeSampa","Brasil","CBO","Operação"),
    ("joao.urzedo","Corporativo","Brasil","CTIO","Corporativo"),
    ("richard.ciriaco","BikeSampa","Brasil","CBO","Operação"),
    ("marcos.paulo","BikeSampa","Brasil","CBO","Operação"),
    ("biatriz.ruas","Corporativo","Brasil","CFO","Corporativo"),
    ("mayra.marquete","Corporativo","Brasil","CBO","Corporativo"),
    ("lucas.messa","Corporativo","Brasil","CBO","Corporativo"),
    ("sabrina.castro","Corporativo","Brasil","CBO","Corporativo"),
    ("demosthenes.junior","BikePE","Brasil","CBO","Operação"),
    ("daniel.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("bruno.valdez","BikeRio","Brasil","CBO","Operação"),
    ("charles.barreto","Corporativo","Brasil","CBO","Corporativo"),
    ("karoline.jesus","BikeSampa","Brasil","CBO","Operação"),
    ("pedro.febronio","BikeSampa","Brasil","CBO","Operação"),
    ("aldo.caterina","Corporativo","Brasil","CEO","Corporativo"),
    ("carlos.spereira","BikeSampa","Brasil","CBO","Operação"),
    ("beatriz.martins","Corporativo","Brasil","CFO","Corporativo"),
    ("gustavo.nascimento","BikeSampa","Brasil","CBO","Operação"),
    ("deborah.medeiros","Corporativo","Brasil","RELGOV","Corporativo"),
    ("thyalison.santos","BikeSampa","Brasil","CBO","Operação"),
    ("newton.sozza","Corporativo","Brasil","CFO","Corporativo"),
    ("alexandre.oliveira","BikeSampa","Brasil","CBO","Operação"),
    ("carlos.gonzaga","BikeSampa","Brasil","CBO","Operação"),
    ("juan.lima","BikeSampa","Brasil","CBO","Operação"),
    ("rafael.melo","BikeSampa","Brasil","CBO","Operação"),
    ("gabriel.svieira","BikeSampa","Brasil","CBO","Operação"),
    ("victor.prado","BikeSampa","Brasil","CBO","Operação"),
    ("kathleen.silva","Corporativo","Brasil","CFO","Corporativo"),
    ("jose.bezerra","BikePE","Brasil","CBO","Operação"),
    ("sergio.silva","BikePE","Brasil","CBO","Operação"),
    ("antonio.rodrigues","BikePE","Brasil","CBO","Operação"),
    ("francisco.junior","BikeRio","Brasil","CBO","Operação"),
    ("gustavo.mendes","BikeRio","Brasil","CBO","Operação"),
    ("matheus.souza","BikeRio","Brasil","CBO","Operação"),
    ("jonathan.lins","BikeRio","Brasil","CBO","Operação"),
    ("hildeberto.lima","BikeRio","Brasil","CBO","Operação"),
    ("vinicius.nascimento","BikeRio","Brasil","CBO","Operação"),
    ("alex.severiano","BikeRio","Brasil","CBO","Operação"),
    ("cassio.souza","BikeRio","Brasil","CBO","Operação"),
    ("eduardo.teixeira","BikeRio","Brasil","CBO","Operação"),
    ("juarez.silva","BikePE","Brasil","CBO","Operação"),
    ("rosenildo.hora","BikeSSA","Brasil","CBO","Operação"),
    ("rafael.mendonca","BikeRio","Brasil","CBO","Operação"),
    ("hildebrando.vieira","BikeRio","Brasil","CBO","Operação"),
    ("bruno.oliveira","BikePE","Brasil","CBO","Operação"),
    ("pedro.hsilva","BikePE","Brasil","CBO","Operação"),
    ("evandro.sousa","BikeRio","Brasil","CBO","Operação"),
    ("silvano.silva","BikeRio","Brasil","CBO","Operação"),
    ("rodrigo.aguiar","BikeRio","Brasil","CBO","Operação"),
    ("wellington.sgoncalves","BikeRio","Brasil","CBO","Operação"),
    ("alexandre.nascimento","BikeRio","Brasil","CBO","Operação"),
    ("felippe.machado","BikePoa","Brasil","CBO","Operação"),
    ("marcio.wasen","BikePoa","Brasil","CBO","Operação"),
    ("jose.fonseca","BikeSSA","Brasil","CBO","Operação"),
    ("ana.menezes","Corporativo","Brasil","CBO","Corporativo"),
    ("nilson.sodre","BikeRio","Brasil","CBO","Operação"),
    ("erica.prudencio","BikeRio","Brasil","CBO","Operação"),
    ("bruno.carvalho","Corporativo","Brasil","CBO","Corporativo"),
    ("tiago.tomita","Corporativo","Brasil","CBO","Corporativo"),
    ("vagner.araujo","BikeRio","Brasil","CBO","Operação"),
    ("joao.reis","BikeRio","Brasil","CBO","Operação"),
    ("andre.mendes","BikeSSA","Brasil","CBO","Operação"),
    ("fernando.carvalho","BikeRio","Brasil","CBO","Operação"),
    ("sheila.barbosa","Corporativo","Brasil","CBO","Corporativo"),
    ("vinicius.qsilva","BikeRio","Brasil","CBO","Operação"),
    ("tiago.almeida","BikeRio","Brasil","CBO","Operação"),
    ("anderson.araujo","BikeRio","Brasil","CBO","Operação"),
    ("rian.basilio","BikeRio","Brasil","CBO","Operação"),
    ("samuel.bezerra","BikePE","Brasil","CBO","Operação"),
    ("douglas.junior","BikePE","Brasil","CBO","Operação"),
    ("antonio.atanasio","BikeRio","Brasil","CBO","Operação"),
    ("thiago.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("fabio.silva","BikeRio","Brasil","CBO","Operação"),
    ("fernanda.marques","Corporativo","Brasil","CBO","Corporativo"),
    ("rodrigo.henrique","BikePE","Brasil","CBO","Operação"),
    ("paulo.sousa","BikeBSB","Brasil","CBO","Operação"),
    ("charles.xavier","BikeSSA","Brasil","CBO","Operação"),
    ("vagner.silva","BikeRio","Brasil","CBO","Operação"),
    ("lucas.costa","BikeRio","Brasil","CBO","Operação"),
    ("paulo.lima","BikeRio","Brasil","CBO","Operação"),
    ("ygor.santos","BikeRio","Brasil","CBO","Operação"),
    ("rodrigo.santos","Corporativo","Brasil","CBO","Corporativo"),
    ("icaro.izabel","BikeSSA","Brasil","CBO","Operação"),
    ("mauricio.maximo","BikeSSA","Brasil","CBO","Operação"),
    ("luiz.santana","BikeRio","Brasil","CBO","Operação"),
    ("alan.jesus","BikePE","Brasil","CBO","Operação"),
    ("emerson.pereira","BikeRio","Brasil","CBO","Operação"),
    ("regivelton.silva","BikeRio","Brasil","CBO","Operação"),
    ("maria.santos","BikePE","Brasil","CBO","Operação"),
    ("marcelo.gomes","BikeRio","Brasil","CBO","Operação"),
    ("rodrigo.cruz","Corporativo","Brasil","CBO","Corporativo"),
    ("magnum.bispo","BikeRio","Brasil","CBO","Operação"),
    ("roniel.oliveira","BikeBSB","Brasil","CBO","Operação"),
    ("jaciara.silva","BikePE","Brasil","CBO","Operação"),
    ("bruna.pinheiro","BikeRio","Brasil","CBO","Operação"),
    ("flavia.gomes","BikeRio","Brasil","CBO","Operação"),
    ("keila.santos","BikeRio","Brasil","CBO","Operação"),
    ("leonardo.mezetti","BikePoa","Brasil","CBO","Operação"),
    ("jhoni.coelho","BikeRio","Brasil","CBO","Operação"),
    ("lino.andrade","BikePE","Brasil","CBO","Operação"),
    ("larissa.souza","Corporativo","Brasil","CBO","Corporativo"),
    ("fagner.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("janilso.ribeiro","BikeRio","Brasil","CBO","Operação"),
    ("eduardo.lourenco","BikeSSA","Brasil","CBO","Operação"),
    ("wanderson.felinto","BikeRio","Brasil","CBO","Operação"),
    ("alex.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("ana.egito","Corporativo","Brasil","CBO","Corporativo"),
    ("camila.luz","Corporativo","Brasil","CBO","Corporativo"),
    ("everton.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("alef.alves","BikeRio","Brasil","CBO","Operação"),
    ("tiago.osilva","BikeRio","Brasil","CBO","Operação"),
    ("carolina.nilo","BikeRio","Brasil","CBO","Operação"),
    ("fabio.cruz","BikeRio","Brasil","CBO","Operação"),
    ("marcelo.teixeira","BikeRio","Brasil","CBO","Operação"),
    ("wanderson.garcia","BikeBSB","Brasil","CBO","Operação"),
    ("elaine.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("paula.oliveira","Corporativo","Brasil","CBO","Corporativo"),
    ("uoshington.silva","BikeRio","Brasil","CBO","Operação"),
    ("cassio.junior","BikePE","Brasil","CBO","Operação"),
    ("cesar.souza","BikeRio","Brasil","CBO","Operação"),
    ("janio.silva","BikePE","Brasil","CBO","Operação"),
    ("maicon.mesquita","BikeRio","Brasil","CBO","Operação"),
    ("raphael.carvalho","BikeRio","Brasil","CBO","Operação"),
    ("eliel.costa","BikePE","Brasil","CBO","Operação"),
    ("diogo.costa","BikeRio","Brasil","CBO","Operação"),
    ("roger.silva","BikeRio","Brasil","CBO","Operação"),
    ("douglas.freitas","BikeRio","Brasil","CBO","Operação"),
    ("bruno.colivera","BikeRio","Brasil","CBO","Operação"),
    ("thiago.santos","BikeRio","Brasil","CBO","Operação"),
    ("raphael.cavalcante","BikeBSB","Brasil","CBO","Operação"),
    ("elton.fernandes","BikeRio","Brasil","CBO","Operação"),
    ("lucas.pereira","BikeRio","Brasil","CBO","Operação"),
    ("rodrigo.monteiro","BikeRio","Brasil","CBO","Operação"),
    ("robert.fernandes","BikeRio","Brasil","CBO","Operação"),
    ("yan.barbosa","BikeRio","Brasil","CBO","Operação"),
    ("felipe.cruver","BikeRio","Brasil","CBO","Operação"),
    ("urvelis.rodriguez","BikeRio","Brasil","CBO","Operação"),
    ("joao.castelo","BikeRio","Brasil","CBO","Operação"),
    ("layrrane.xavier","Corporativo","Brasil","CBO","Corporativo"),
    ("hiolita.mattiuzzi","BikeCuritiba","Brasil","CBO","Operação"),
    ("douglas.pereira","BikeCuritiba","Brasil","CBO","Operação"),
    ("angelo.almeida","BikeRio","Brasil","CBO","Operação"),
    ("marcio.fernandes","BikeRio","Brasil","CBO","Operação"),
    ("nathalia.paes","Corporativo","Brasil","CBO","Corporativo"),
    ("gabrielle.faria","Corporativo","Brasil","CBO","Corporativo"),
    ("yasmim.leao","Corporativo","Brasil","CBO","Corporativo"),
    ("priscila.pascoal","Corporativo","Brasil","CBO","Corporativo"),
    ("jose.ferreira","BikePE","Brasil","CBO","Operação"),
    ("andrea.moreno","BikeRio","Brasil","CBO","Operação"),
    ("akacio.santos","BikePE","Brasil","CBO","Operação"),
    ("carlos.henrique","BikePE","Brasil","CBO","Operação"),
    ("wellerson.valandro","BikePoa","Brasil","CBO","Operação"),
    ("anderson.verissimo","BikeRio","Brasil","CBO","Operação"),
    ("thiago.mohr","BikeCuritiba","Brasil","CBO","Operação"),
    ("bruno.assis","BikeFloripa","Brasil","CBO","Operação"),
    ("luiz.velozo","BikeCuritiba","Brasil","CBO","Operação"),
    ("giovanni.castelletti","BikeFloripa","Brasil","CBO","Operação"),
    ("yoswual.serrano","BikeRio","Brasil","CBO","Operação"),
    ("aline.oliveira","BikeFloripa","Brasil","CBO","Operação"),
    ("samira.franco","BikeCuritiba","Brasil","CBO","Operação"),
    ("gustavo.franca","BikeRio","Brasil","CBO","Operação"),
    ("simone.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("alexsandro.silva","BikeSSA","Brasil","CBO","Operação"),
    ("wellington.lopes","BikeCuritiba","Brasil","CBO","Operação"),
    ("gilson.ribeiro","BikeSSA","Brasil","CBO","Operação"),
    ("christian.estanga","BikeRio","Brasil","CBO","Operação"),
    ("deborah.diniz","BikeFloripa","Brasil","CBO","Operação"),
    ("julio.campos","BikeBH","Brasil","CBO","Operação"),
    ("leonardo.bpereira","BikePoa","Brasil","CBO","Operação"),
    ("francilio.silva","BikeRio","Brasil","CBO","Operação"),
    ("messias.silva","BikeBH","Brasil","CBO","Operação"),
    ("lucas.ssouza","BikeFloripa","Brasil","CBO","Operação"),
    ("danilo.farias","BikeRio","Brasil","CBO","Operação"),
    ("marcelo.sousa","BikeRio","Brasil","CBO","Operação"),
    ("ivan.albuquerque","BikeRio","Brasil","CBO","Operação"),
    ("chaeane.taisses","BikePoa","Brasil","CBO","Operação"),
    ("alexia.bezerra","BikeRio","Brasil","CBO","Operação"),
    ("ravel.silva","BikeRio","Brasil","CBO","Operação"),
    ("omar.martinez","BikeRio","Brasil","CBO","Operação"),
    ("emerson.costa","BikeRio","Brasil","CBO","Operação"),
    ("fernando.novais","BikeSSA","Brasil","CBO","Operação"),
    ("jean.silva","BikePoa","Brasil","CBO","Operação"),
    ("bruno.pereira","BikeRio","Brasil","CBO","Operação"),
    ("gleyson.sousa","BikeRio","Brasil","CBO","Operação"),
    ("wagner.krauspenhar","BikePoa","Brasil","CBO","Operação"),
    ("gabriel.pessoa","BikeSSA","Brasil","CBO","Operação"),
    ("anatalio.santos","BikeRio","Brasil","CBO","Operação"),
    ("alexander.pinheiro","BikeRio","Brasil","CBO","Operação"),
    ("katriel.silva","BikeRio","Brasil","CBO","Operação"),
    ("fernando.monteiro","BikeRio","Brasil","CBO","Operação"),
    ("bruno.campos","BikeBH","Brasil","CBO","Operação"),
    ("janaina.albuquerque","BikePE","Brasil","CBO","Operação"),
    ("marcos.medeiros","BikeRio","Brasil","CBO","Operação"),
    ("davi.barbosa","BikeRio","Brasil","CBO","Operação"),
    ("fernanda.aguiar","BikeRio","Brasil","CBO","Operação"),
    ("arthur.bsilva","BikePE","Brasil","CBO","Operação"),
    ("andrea.silva","BikeRio","Brasil","CBO","Operação"),
    ("maciel.bezerra","BikeRio","Brasil","CBO","Operação"),
    ("rennan.queiroz1","BikeRio","Brasil","CBO","Operação"),
    ("jose.deguchi","BikeCuritiba","Brasil","CBO","Operação"),
    ("luiz.sbarros","BikeRio","Brasil","CBO","Operação"),
    ("douglas.asilva","BikeRio","Brasil","CBO","Operação"),
    ("lucas.nunes","BikePoa","Brasil","CBO","Operação"),
    ("raphael.mancebo","BikeRio","Brasil","CBO","Operação"),
    ("lucas.kozowiski","BikeCuritiba","Brasil","CBO","Operação"),
    ("eduardo.andrade","BikeFloripa","Brasil","CBO","Operação"),
    ("alan.conceicao","BikeSSA","Brasil","CBO","Operação"),
    ("vinicius.chalef","BikeRio","Brasil","CBO","Operação"),
    ("diorgenes.souza","BikeRio","Brasil","CBO","Operação"),
    ("cayo.garcia","BikeRio","Brasil","CBO","Operação"),
    ("felipe.scosta","BikeRio","Brasil","CBO","Operação"),
    ("lorestin.souza","BikeRio","Brasil","CBO","Operação"),
    ("bruno.guilherme","BikeRio","Brasil","CBO","Operação"),
    ("assuero.santos","BikePE","Brasil","CBO","Operação"),
    ("vander.souza","BikeRio","Brasil","CBO","Operação"),
    ("wellington.cunha","BikeRio","Brasil","CBO","Operação"),
    ("larissa.soares","BikeRio","Brasil","CBO","Operação"),
    ("larissa.mattos","BikeRio","Brasil","CBO","Operação"),
    ("andre.prestes","BikeCuritiba","Brasil","CBO","Operação"),
    ("danielle.silva","BikePE","Brasil","CBO","Operação"),
    ("jose.asantos","BikeSSA","Brasil","CBO","Operação"),
    ("thiago.steixeira","BikeSSA","Brasil","CBO","Operação"),
    ("vinicius.basilio","BikeRio","Brasil","CBO","Operação"),
    ("lucas.gteixeira","BikeRio","Brasil","CBO","Operação"),
    ("rodrigo.eskenazi","BikeRio","Brasil","CBO","Operação"),
    ("ronielle.carvalho","BikeRio","Brasil","CBO","Operação"),
    ("derick.borges","BikeRio","Brasil","CBO","Operação"),
    ("thassio.leite","BikeRio","Brasil","CBO","Operação"),
    ("julio.goivaes","BikeRio","Brasil","CBO","Operação"),
    ("wallace.carneiro","Corporativo","Brasil","CBO","Corporativo"),
    ("leoneir.martins","BikeRio","Brasil","CBO","Operação"),
    ("ramon.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("francisco.filho","BikeRio","Brasil","CBO","Operação"),
    ("marcelo.lima","BikeRio","Brasil","CBO","Operação"),
    ("george.magalhaes","BikeRio","Brasil","CBO","Operação"),
    ("jacson.fernandes","BikeFloripa","Brasil","CBO","Operação"),
    ("carlos.rodrigues","BikeRio","Brasil","CBO","Operação"),
    ("raphael.lacerda","BikeBSB","Brasil","CBO","Operação"),
    ("luiz.marques","BikeRio","Brasil","CBO","Operação"),
    ("joao.miguel","BikeFloripa","Brasil","CBO","Operação"),
    ("roberto.paula","BikeFloripa","Brasil","CBO","Operação"),
    ("humberto.lopes","BikeSSA","Brasil","CBO","Operação"),
    ("adam.silva","BikeRio","Brasil","CBO","Operação"),
    ("anderson.rodrigues","BikeSSA","Brasil","CBO","Operação"),
    ("joao.cardoso","BikeRio","Brasil","CBO","Operação"),
    ("maria.silva","BikeRio","Brasil","CBO","Operação"),
    ("jeisson.gordillo","BikeRio","Brasil","CBO","Operação"),
    ("emerson.jesus","BikeRio","Brasil","CBO","Operação"),
    ("davidson.filho","BikeRio","Brasil","CBO","Operação"),
    ("wagner.silva","BikeRio","Brasil","CBO","Operação"),
    ("alexander.soares","BikeRio","Brasil","CBO","Operação"),
    ("daniel.ssilva","BikeBH","Brasil","CBO","Operação"),
    ("victor.miranda","BikeRio","Brasil","CBO","Operação"),
    ("sidney.junior","BikeCuritiba","Brasil","CBO","Operação"),
    ("higor.couto","BikeCuritiba","Brasil","CBO","Operação"),
    ("charles.rosa","BikePoa","Brasil","CBO","Operação"),
    ("jhonnatan.bonfim","BikeRio","Brasil","CBO","Operação"),
    ("pedro.miranda","BikeBH","Brasil","CBO","Operação"),
    ("alan.alves","BikeBH","Brasil","CBO","Operação"),
    ("rafael.lacerda","BikeBSB","Brasil","CBO","Operação"),
    ("kethlen.faria","BikeRio","Brasil","CBO","Operação"),
    ("leandro.lucio","BikeRio","Brasil","CBO","Operação"),
    ("bruno.machado","BikeRio","Brasil","CBO","Operação"),
    ("wilian.junior","BikeRio","Brasil","CBO","Operação"),
    ("paulo.almeida","BikeSSA","Brasil","CBO","Operação"),
    ("samir.macedo","BikeFloripa","Brasil","CBO","Operação"),
    ("lucas.goes","BikeSSA","Brasil","CBO","Operação"),
    ("artur.vargas","BikePoa","Brasil","CBO","Operação"),
    ("brayan.yanez","BikePoa","Brasil","CBO","Operação"),
    ("israel.filho","BikeSSA","Brasil","CBO","Operação"),
    ("ana.campiglia","BikeRio","Brasil","CBO","Operação"),
    ("joseane.silva","BikeBSB","Brasil","CBO","Operação"),
    ("eduardo.oliveira","BikePoa","Brasil","CBO","Operação"),
    ("fernanda.rosa","BikePoa","Brasil","CBO","Operação"),
    ("sergio.oliveira","BikePE","Brasil","CBO","Operação"),
    ("patrick.moro","BikePoa","Brasil","CBO","Operação"),
    ("felipe.rcarvalho","BikeBSB","Brasil","CBO","Operação"),
    ("kaue.krum","BikeCuritiba","Brasil","CBO","Operação"),
    ("tereza.morais","BikeRio","Brasil","CBO","Operação"),
    ("carlos.bezerra","BikeSSA","Brasil","CBO","Operação"),
    ("fernanda.araujo","BikeSSA","Brasil","CBO","Operação"),
    ("wellington.paim","BikeSSA","Brasil","CBO","Operação"),
    ("lazaro.santos","BikeSSA","Brasil","CBO","Operação"),
    ("kiaku.nkunga","BikeRio","Brasil","CBO","Operação"),
    ("carlos.peche","BikeRio","Brasil","CBO","Operação"),
    ("marcia.lucena","BikeBSB","Brasil","CBO","Operação"),
    ("sarah.silva","BikeRio","Brasil","CBO","Operação"),
    ("ismael.silva","BikePoa","Brasil","CBO","Operação"),
    ("laos.rosa","BikePoa","Brasil","CBO","Operação"),
    ("emerson.santos","BikeBH","Brasil","CBO","Operação"),
    ("daniel.martins","BikeRio","Brasil","CBO","Operação"),
    ("italo.nuno","BikeSSA","Brasil","CBO","Operação"),
    ("edgar.dias","BikeBH","Brasil","CBO","Operação"),
    ("anderson.anjos","BikeSSA","Brasil","CBO","Operação"),
    ("cesar.marquez","BikeBSB","Brasil","CBO","Operação"),
    ("lucas.cabral","BikeBH","Brasil","CBO","Operação"),
    ("fabio.teixeira","BikeRio","Brasil","CBO","Operação"),
    ("bruno.brito","BikeSSA","Brasil","CBO","Operação"),
    ("anderson.barreto","BikeSSA","Brasil","CBO","Operação"),
    ("jairo.souza","BikeRio","Brasil","CBO","Operação"),
    ("wallas.santos","BikeSSA","Brasil","CBO","Operação"),
    ("darliany.souza","BikeBSB","Brasil","CBO","Operação"),
    ("elves.silva","BikePE","Brasil","CBO","Operação"),
    ("juliano.linhares","BikePoa","Brasil","CBO","Operação"),
    ("eduardo.cunha","BikePE","Brasil","CBO","Operação"),
    ("marcel.silva","BikePE","Brasil","CBO","Operação"),
    ("lucas.soares","BikeSSA","Brasil","CBO","Operação"),
    ("caique.almeida","BikeSSA","Brasil","CBO","Operação"),
    ("guilherme.osilva","BikeRio","Brasil","CBO","Operação"),
    ("thalyta.silva","BikePE","Brasil","CBO","Operação"),
    ("kenya.costa","BikePoa","Brasil","CBO","Operação"),
    ("erico.oliveira","BikeFloripa","Brasil","CBO","Operação"),
    ("maira.neisenger","BikeFloripa","Brasil","CBO","Operação"),
    ("wesley.santos","BikePE","Brasil","CBO","Operação"),
    ("junio.hypolito","BikeBH","Brasil","CBO","Operação"),
    ("bruna.santos","BikeSSA","Brasil","CBO","Operação"),
    ("edimeia.jesus","BikeSSA","Brasil","CBO","Operação"),
    ("luis.santos","BikeSSA","Brasil","CBO","Operação"),
    ("ricardo.teixeira","BikeRio","Brasil","CBO","Operação"),
    ("renan.andrade","BikeRio","Brasil","CBO","Operação"),
    ("fabio.franca","BikeRio","Brasil","CBO","Operação"),
    ("julia.pires","BikeRio","Brasil","CBO","Operação"),
    ("leandro.souza","BikeRio","Brasil","CBO","Operação"),
    ("rosa.barbosa","BikeRio","Brasil","CBO","Operação"),
    ("luiza.almeida","BikeBH","Brasil","CBO","Operação"),
    ("luiz.eduardo","BikeRio","Brasil","CBO","Operação"),
    ("emerson.souza","Corporativo","Brasil","CBO","Corporativo"),
    ("evaldo.lima","BikeRio","Brasil","CBO","Operação"),
    ("victor.teixeira","BikeRio","Brasil","CBO","Operação"),
    ("tallita.marques","BikeRio","Brasil","CBO","Corporativo"),
    ("dionatan.premibida","BikeCuritiba","Brasil","CBO","Operação"),
    ("pedro.almeida","BikeRio","Brasil","CBO","Operação"),
    ("gilmar.junior","BikeRio","Brasil","CBO","Operação"),
    ("washington.felix","BikeBH","Brasil","CBO","Operação"),
    ("ricardo.sodre","BikeSSA","Brasil","CBO","Operação"),
    ("lucas.cardoso","BikeRio","Brasil","CBO","Operação"),
    ("elias.santos","BikeRio","Brasil","CBO","Operação"),
    ("welbert.souza","BikeRio","Brasil","CBO","Operação"),
    ("carla.bezerra","BikeRio","Brasil","CBO","Operação"),
    ("marcio.silva","BikeRio","Brasil","CBO","Operação"),
    ("darcio.junior","BikeBH","Brasil","CBO","Operação"),
    ("victor.jorge","BikeRio","Brasil","CBO","Operação"),
    ("isabela.duarte","BikeRio","Brasil","CBO","Operação"),
    ("marcio.carvalho","BikeRio","Brasil","CBO","Operação"),
    ("pedro.moehleck","BikeRio","Brasil","CBO","Operação"),
    ("jociel.pereira","BikeSSA","Brasil","CBO","Operação"),
    ("alexandre.fonseca","BikeRio","Brasil","CBO","Operação"),
    ("anderson.paulo","BikeRio","Brasil","CBO","Operação"),
    ("savio.caldeira","BikeBH","Brasil","CBO","Operação"),
    ("moacir.junior","BikeRio","Brasil","CBO","Operação"),
    ("lucas.valenca","BikeFloripa","Brasil","CBO","Operação"),
    ("leandro.pires","BikeFloripa","Brasil","CBO","Operação"),
    ("caique.santos","BikeBH","Brasil","CBO","Operação"),
    ("joao.cintra","BikeBH","Brasil","CBO","Operação"),
    ("thiago.osantos","BikePoa","Brasil","CBO","Operação"),
    ("moises.gomes","BikeRio","Brasil","CBO","Operação"),
    ("eder.costa","BikeCuritiba","Brasil","CBO","Operação"),
    ("luiz.pereira","BikeBSB","Brasil","CBO","Operação"),
    ("paulo.sergio","BikeSSA","Brasil","CBO","Operação"),
    ("thalles.silva","BikeRio","Brasil","CBO","Operação"),
    ("omar.aguilera","BikeFloripa","Brasil","CBO","Operação"),
    ("gabriel.siqueira","BikePoa","Brasil","CBO","Operação"),
    ("marcos.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("jhonatan.costa","BikeRio","Brasil","CBO","Operação"),
    ("vinicius.ribeiro","BikeRio","Brasil","CBO","Operação"),
    ("carlos.eduardo","BikeRio","Brasil","CBO","Operação"),
    ("carlos.freitas","BikePoa","Brasil","CBO","Operação"),
    ("guilherme.vaz","BikePoa","Brasil","CBO","Operação"),
    ("cleyton.silva","BikeRio","Brasil","CBO","Operação"),
    ("eduardo.sebastiao","BikeBH","Brasil","CBO","Operação"),
    ("vinicius.fernandes","BikeRio","Brasil","CBO","Operação"),
    ("jonathan.avelino","BikeRio","Brasil","CBO","Operação"),
    ("paulo.lopes","BikeBH","Brasil","CBO","Operação"),
    ("brendo.alcantara","BikeBSB","Brasil","CBO","Operação"),
    ("regis.silva","BikePoa","Brasil","CBO","Operação"),
    ("leonardo.mendes","BikePoa","Brasil","CBO","Operação"),
    ("gerson.cabral","BikeRio","Brasil","CBO","Operação"),
    ("wagner.machado","BikeFloripa","Brasil","CBO","Operação"),
    ("alexsandro.weretycki","BikeCuritiba","Brasil","CBO","Operação"),
    ("mariana.sousa","BikeRio","Brasil","CBO","Operação"),
    ("marcon.deus","BikeRio","Brasil","CBO","Operação"),
    ("filipe.medrado","BikeSSA","Brasil","CBO","Operação"),
    ("ibson.allendes","BikeRio","Brasil","CBO","Operação"),
    ("vitoria.safadi","BikeRio","Brasil","CBO","Operação"),
    ("luan.moura","BikeRio","Brasil","CBO","Operação"),
    ("josue.almeida","BikeRio","Brasil","CBO","Operação"),
    ("denis.silva","BikeRio","Brasil","CBO","Operação"),
    ("michael.alves","BikeRio","Brasil","CBO","Operação"),
    ("maria.siqueira","BikeRio","Brasil","CBO","Operação"),
    ("paloma.silva","Corporativo","Brasil","CBO","Corporativo"),
    ("gabriel.souza","BikeRio","Brasil","CBO","Operação"),
    ("marco.braz","BikeRio","Brasil","CBO","Operação"),
    ("matheus.rocha","BikeRio","Brasil","CBO","Operação"),
    ("sergio.gomes","BikeRio","Brasil","CBO","Operação"),
    ("lincoln.fernandes","BikeRio","Brasil","CBO","Operação"),
    ("pedro.kronitzky","BikePoa","Brasil","CBO","Operação"),
    ("anderson.oliveira","BikeRio","Brasil","CBO","Operação"),
    ("luis.gomes","BikeRio","Brasil","CBO","Operação"),
    ("jediel.silva","BikeSampa","Brasil","CBO","Operação"),
    ("gislandia.cardoso","BikeSampa","Brasil","CBO","Operação"),
    ("damiao.santana","CD Extrema","Brasil","CBO","Operação"),
    ("ana.martins","CD Extrema","Brasil","CBO","Operação"),
    ("hector.bolivar","CD Extrema","Brasil","CBO","Operação"),
    ("wesley.herculano","CD Extrema","Brasil","CBO","Operação"),
    ("everton.dias","CD Extrema","Brasil","CBO","Operação"),
    ("maurilio.junior","CD Extrema","Brasil","CBO","Operação"),
    ("leia.grecco","CD Extrema","Brasil","CBO","Operação"),
    ("cesar.siso","CD Extrema","Brasil","CBO","Operação"),
    ("natalia.ronchi","BAEcobici","Argentina","B2B","Corporativo"),
    ("castano.rodriguez","BAEcobici","Argentina","CBO","Operação"),
    ("gabriel.sorace","BAEcobici","Argentina","CBO","Operação"),
    ("hector.quiroga","BAEcobici","Argentina","CBO","Operação"),
    ("cristian.cordova","BAEcobici","Argentina","CBO","Operação"),
    ("jonatan.barrientos","BAEcobici","Argentina","CBO","Operação"),
    ("martin.diaz","BAEcobici","Argentina","CBO","Operação"),
    ("sebastian.frattura","BAEcobici","Argentina","CBO","Operação"),
    ("pablo.lopez","BAEcobici","Argentina","CBO","Corporativo"),
    ("henry.gisbert","BAEcobici","Argentina","CBO","Operação"),
    ("richar.riveros","BAEcobici","Argentina","CBO","Operação"),
    ("ignacio.romero","BAEcobici","Argentina","CBO","Operação"),
    ("diego.tello","BAEcobici","Argentina","CBO","Operação"),
    ("tamara.szydlowski","BAEcobici","Argentina","CBO","Operação"),
    ("marian.dapueto","BAEcobici","Argentina","CBO","Operação"),
    ("luciano.varela","BAEcobici","Argentina","CBO","Operação"),
    ("leticia.torres","BAEcobici","Argentina","CBO","Operação"),
    ("jessica.suarez","BAEcobici","Argentina","CBO","Operação"),
    ("ezequiel.escalante","BAEcobici","Argentina","CBO","Operação"),
    ("jose.molina","BAEcobici","Argentina","CBO","Operação"),
    ("manuel.mansilla","BAEcobici","Argentina","CBO","Operação"),
    ("gabriel.pino","BAEcobici","Argentina","CBO","Corporativo"),
    ("jonatan.carabajal","BAEcobici","Argentina","CBO","Operação"),
    ("mario.rojas","BAEcobici","Argentina","CBO","Operação"),
    ("celeste.persuh","BAEcobici","Argentina","CBO","Operação"),
    ("claudio.arguello","BAEcobici","Argentina","CBO","Operação"),
    ("roberto.medori","BAEcobici","Argentina","CBO","Operação"),
    ("eduardo.guzman","BAEcobici","Argentina","CBO","Operação"),
    ("joam.galea","BAEcobici","Argentina","CBO","Operação"),
    ("jonathan.gonzalez","BAEcobici","Argentina","CBO","Operação"),
    ("hector.zeballos","BAEcobici","Argentina","CBO","Operação"),
    ("aldana.buendia","BAEcobici","Argentina","CBO","Operação"),
    ("julian.prado","BAEcobici","Argentina","CBO","Operação"),
    ("gonzalo.ferreyra","BAEcobici","Argentina","CBO","Operação"),
    ("diego.paredes","BAEcobici","Argentina","CBO","Operação"),
    ("erick.marcano","BAEcobici","Argentina","CBO","Operação"),
    ("walter.sorella","BAEcobici","Argentina","CBO","Operação"),
    ("leonardo.dominguez","BAEcobici","Argentina","CBO","Operação"),
    ("roman.marek","BAEcobici","Argentina","CBO","Operação"),
    ("romualdo.toconas","BAEcobici","Argentina","CBO","Operação"),
    ("javier.orellano","BAEcobici","Argentina","CBO","Operação"),
    ("jose.martinez","BAEcobici","Argentina","CBO","Operação"),
    ("milton.velardes","BAEcobici","Argentina","CBO","Operação"),
    ("ruben.gonzalez","BAEcobici","Argentina","CBO","Operação"),
    ("lucas.pollet","BAEcobici","Argentina","CBO","Operação"),
    ("lucas.caceres","BAEcobici","Argentina","CBO","Operação"),
    ("jose.sanchez","BAEcobici","Argentina","CBO","Operação"),
    ("emanuel.perez","BAEcobici","Argentina","CBO","Operação"),
    ("pablo.boyer","BAEcobici","Argentina","CBO","Operação"),
    ("julio.carabajal","BAEcobici","Argentina","CBO","Operação"),
    ("diego.moreno","BAEcobici","Argentina","CBO","Operação"),
    ("laila.slavutzky","BAEcobici","Argentina","CBO","Operação"),
    ("luciano.escalante","BAEcobici","Argentina","CBO","Operação"),
    ("nicolas.yanicelli","BAEcobici","Argentina","CBO","Operação"),
    ("juan.gavilan","BAEcobici","Argentina","CBO","Operação"),
    ("armando.arias","BAEcobici","Argentina","CBO","Operação"),
    ("braian.vassia","BAEcobici","Argentina","CBO","Operação"),
    ("diego.iluchko","BAEcobici","Argentina","CBO","Operação"),
    ("ligotti.adrian","BAEcobici","Argentina","CBO","Operação"),
    ("alejandro.castillo","BAEcobici","Argentina","CBO","Operação"),
    ("brian.vicenzo","BAEcobici","Argentina","CBO","Operação"),
    ("godoy.segundo","BAEcobici","Argentina","CBO","Operação"),
    ("nahuel.di","BAEcobici","Argentina","CBO","Operação"),
    ("jesica.ferrer","BAEcobici","Argentina","CBO","Corporativo"),
    ("julieta.rey","BAEcobici","Argentina","B2B","Corporativo"),
    ("castillo.maximiliano","BAEcobici","Argentina","CBO","Operação"),
    ("mauricio.silvero","BAEcobici","Argentina","CBO","Operação"),
    ("franco.espejo","BAEcobici","Argentina","CBO","Operação"),
    ("cintia.grispo","BAEcobici","Argentina","CBO","Corporativo"),
    ("edson.calle","BAEcobici","Argentina","CBO","Operação"),
    ("antonio.ezequiel","BAEcobici","Argentina","CBO","Operação"),
    ("gonzalo.risso","BAEcobici","Argentina","CBO","Operação"),
    ("diego.alvarenque","BAEcobici","Argentina","CBO","Operação"),
    ("mayer.damian","BAEcobici","Argentina","CBO","Operação"),
    ("zotelo.agustin","BAEcobici","Argentina","CBO","Operação"),
    ("jesica.zanabria","BAEcobici","Argentina","CBO","Corporativo"),
    ("silvana.jaimez","BAEcobici","Argentina","CFO","Corporativo"),
    ("julian.cevey","BAEcobici","Argentina","CBO","Operação"),
    ("ibanes.emanuel","BAEcobici","Argentina","CBO","Operação"),
    ("lucas.godoy","BAEcobici","Argentina","CBO","Operação"),
    ("joaquin.benitez","BAEcobici","Argentina","CBO","Operação"),
    ("asael.federico","BAEcobici","Argentina","CBO","Operação"),
    ("micaela.castano","BAEcobici","Argentina","CFO","Corporativo"),
    ("barbara.fagnani","BAEcobici","Argentina","CFO","Corporativo"),
    ("thiago.rodriguez","BAEcobici","Argentina","CBO","Operação"),
    ("sabrina.ortellado","BAEcobici","Argentina","CBO","Operação"),
    ("thiago.quiroz","BAEcobici","Argentina","CBO","Operação"),
    ("iago.riveiro","BAEcobici","Argentina","CBO","Operação"),
    ("andres.cardozo","BAEcobici","Argentina","CBO","Operação"),
    ("anthony.stivens","BAEcobici","Argentina","CBO","Operação"),
    ("edgar.aguero","BAEcobici","Argentina","CBO","Operação"),
    ("milena.oviedo","BAEcobici","Argentina","CBO","Corporativo"),
    ("valentina.almentero","BAEcobici","Argentina","CBO","Corporativo"),
    ("lucas.omil","BAEcobici","Argentina","CBO","Operação"),
    ("nicolas.leiva","BAEcobici","Argentina","CBO","Operação"),
    ("sofia.simiele","BAEcobici","Argentina","CBO","Operação"),
    ("ignacio.herrera","BAEcobici","Argentina","CBO","Operação"),
    ("yonatan.sales","BAEcobici","Argentina","CBO","Operação"),
    ("alan.quinas","BAEcobici","Argentina","CBO","Operação"),
    ("nataly.rodriguez","BAEcobici","Argentina","CBO","Operação"),
    ("leonardo.kowalczuk","BAEcobici","Argentina","CBO","Operação"),
    ("julian.gonzalez","BAEcobici","Argentina","CBO","Operação"),
    ("marcos.fernandez","BAEcobici","Argentina","CBO","Operação"),
    ("mario.romeo","BAEcobici","Argentina","CBO","Operação"),
    ("franco.gonzalez","BAEcobici","Argentina","CBO","Operação"),
    ("franco.girard","BAEcobici","Argentina","CBO","Operação"),
    ("javiera.pinto","BikeSantiago","Chile","CBO","Corporativo"),
    ("matias.barros","BikeSantiago","Chile","CBO","Operação"),
    ("felipe.ruiz","BikeSantiago","Chile","CBO","Operação"),
    ("jose.espinoza","BikeSantiago","Chile","CBO","Corporativo"),
    ("alexander.valderrama","BikeSantiago","Chile","CBO","Operação"),
    ("alejandra.donoso","BikeSantiago","Chile","CBO","Operação"),
    ("christian.cerda","BikeSantiago","Chile","CBO","Operação"),
    ("alexander.acosta","BikeSantiago","Chile","CBO","Operação"),
    ("rebeca.paredes","BikeSantiago","Chile","CBO","Corporativo"),
    ("luis.gonzalez","BikeSantiago","Chile","CBO","Operação"),
    ("matteo.vergara","BikeSantiago","Chile","CBO","Operação"),
    ("ednailton.souza","BikeSantiago","Chile","CBO","Operação"),
    ("bastian.caceres","BikeSantiago","Chile","CBO","Operação"),
    ("raul.reyes","BikeSantiago","Chile","CBO","Operação"),
    ("daniela.izquierdo","BikeSantiago","Chile","CBO","Operação"),
    ("michell.soriano","BikeSantiago","Chile","CFO","Corporativo"),
    ("yohana.navarro","BikeSantiago","Chile","CFO","Corporativo"),
    ("cristian.soto","BikeSantiago","Chile","CBO","Operação"),
    ("claudia.toro","BikeSantiago","Chile","CFO","Corporativo"),
    ("miguel.monroy","BikeSantiago","Chile","CBO","Operação"),
    ("ximena.barrera","BikeSantiago","Chile","CFO","Corporativo"),
    ("allan.loyola","BikeSantiago","Chile","CBO","Operação"),
    ("fernando.herrera","BikeSantiago","Chile","CBO","Operação"),
    ("carlos.regular","BikeSantiago","Chile","CBO","Operação"),
    ("mauricio.henriquez","BikeSantiago","Chile","CBO","Operação"),
    ("joshua.perez","BikeSantiago","Chile","CBO","Corporativo"),
    ("felipe.salazar","BikeSantiago","Chile","CBO","Operação"),
    ("joaquin.gonzalez","BikeSantiago","Chile","CBO","Operação"),
    ("leonardo.pinilla","BikeSantiago","Chile","CBO","Operação"),
    ("jonathan.nunez","BikeSantiago","Chile","CBO","Operação"),
    ("enmanuel.garcia","BikeSantiago","Chile","CBO","Operação"),
    ("alexander.bustos","BikeSantiago","Chile","CBO","Operação"),
    ("victoria.pericana","BikeSantiago","Chile","CBO","Operação"),
    ("inti.flores","BikeSantiago","Chile","CBO","Operação"),
    ("daniel.navarrete","BikeSantiago","Chile","CBO","Operação"),
    ("matias.figueroa","BikeSantiago","Chile","CBO","Operação"),
    ("eduardo.caceres","BikeSantiago","Chile","CBO","Operação"),
    ("jorge.escobar","BikeSantiago","Chile","CBO","Operação"),
    ("cristobal.castillo","BikeSantiago","Chile","CBO","Operação"),
    ("jorge.ferraro","BikeSantiago","Chile","CBO","Operação"),
    ("christopher.lineros","BikeSantiago","Chile","CBO","Operação"),
    ("camila.acosta","BikeBogota","Colômbia","CFO","Corporativo"),
    ("jhoan.hurtado","BikeBogota","Colômbia","CBO","Operação"),
    ("jeison.reyes","BikeBogota","Colômbia","CBO","Operação"),
    ("july.velasco","BikeBogota","Colômbia","CBO","Corporativo"),
    ("andres.amador","BikeBogota","Colômbia","CBO","Operação"),
    ("juan.ortiz","BikeBogota","Colômbia","CFO","Corporativo"),
    ("carolina.rodriguez","BikeBogota","Colômbia","CBO","Corporativo"),
    ("leidy.torres","BikeBogota","Colômbia","CBO","Corporativo"),
    ("kevin.pineda","BikeBogota","Colômbia","RELGOV","Corporativo"),
    ("liz.ussa","BikeBogota","Colômbia","CBO","Operação"),
    ("paola.ladino","BikeBogota","Colômbia","CBO","Operação"),
    ("diana.aranda","BikeBogota","Colômbia","CBO","Corporativo"),
    ("angie.reina","BikeBogota","Colômbia","CBO","Operação"),
    ("oscar.rodriguez","BikeBogota","Colômbia","CBO","Operação"),
    ("janner.garcia","BikeBogota","Colômbia","CBO","Operação"),
    ("laura.vasquez","BikeBogota","Colômbia","CBO","Operação"),
    ("oscar.rojas","BikeBogota","Colômbia","CBO","Operação"),
    ("luisa.restrepo","BikeBogota","Colômbia","CBO","Operação"),
]

USER_MAP = {}
for row in USERS_RAW:
    h, praca, pais, diretoria, adm_corp = row
    key = h.strip().lower()
    praca = "BikeSampa" if praca.strip().lower() == "riviera" else praca.strip()
    USER_MAP[key] = {"praca": praca, "pais": pais.strip(),
                     "diretoria": diretoria.strip(), "adm_corp": adm_corp.strip()}

def build_output(raw):
    standings = raw.get("standings", [])
    finished  = raw.get("finishedMatches", [])
    enriched, unmatched = [], []
    for e in standings:
        u = e.get("user", {})
        handle = (u.get("handle") or "").strip().lower()
        info = USER_MAP.get(handle)
        if not info:
            unmatched.append(handle)
            info = {"praca":"Outros","pais":"Outros","diretoria":"Outros","adm_corp":"Outros"}
        enriched.append({
            "rank":             e.get("rank"),
            "totalPoints":      e.get("totalPoints", 0),
            "prevPosition":     e.get("prevPosition", 0),
            "prevTotalPoints":  e.get("prevTotalPoints", 0),
            "predictionsCount": e.get("predictionsCount", 0),
            "exactScoreCount":  e.get("exactScoreCount", 0),
            "correctWinnerCount": e.get("correctWinnerCount", 0),
            "handle":      handle,
            "displayName": u.get("displayName", handle),
            "praca":       info["praca"],
            "pais":        info["pais"],
            "diretoria":   info["diretoria"],
            "adm_corp":    info["adm_corp"],
        })
    return {
        "updatedAt": datetime.utcnow().isoformat() + "Z",
        "finishedMatchesCount": len(finished),
        "standings": enriched,
        "unmatchedHandles": unmatched
    }

if __name__ == "__main__":
    print("Renovando JWT...")
    jwt = get_fresh_jwt()
    print("Buscando leaderboard...")
    raw = fetch_leaderboard(jwt)
    output = build_output(raw)
    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    n = len(output["standings"])
    j = output["finishedMatchesCount"]
    print(f"OK — {n} participantes, {j} jogos encerrados")
    if output["unmatchedHandles"]:
        print(f"Sem match: {output['unmatchedHandles']}")
